<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

use App\Models\Pharmacies\Product;
use App\Models\Pharmacies\Receiving;
use App\Models\Pharmacies\ReceivingItem;
use App\Models\Pharmacies\Batch;

class ImportSamuProducts extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'command:importSamuProducts';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $receiving = new Receiving();$receiving->date = now();$receiving->establishment_id = 34;$receiving->pharmacy_id = 6;$receiving->notes = "CARGA INICIAL";$receiving->user_id = 18007001;$receiving->save();
        $product = new Product();$product->barcode = '100001153';$product->name = 'Kit determinación glucosa cinta + lanceta (1+1)';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001457';$product->name = 'Torula Algodón Hidrófilo 0,5g  x 1000 UD';$product->unit = 'BS';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '17805633006111';$product->name = 'Jeringa Luer Lock 20mL sin Aguja estéril ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000294';$product->name = 'Branula IV 22G ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1000002899';$product->name = 'Branula IV 18G ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000086';$product->name = 'Alcohol Desnaturalizado 70° x 1L ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000087';$product->name = 'Alcohol Desnaturalizado 70° x 250mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '682607559435';$product->name = 'Medidor Glucosa en Sangre On-Call Extra Modelo 0GM-191';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000708';$product->name = 'Gel P/Electrocardiograma TU 220 A 280 g ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000288';$product->name = 'Branula IV 16G ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000997';$product->name = 'Mascarilla Nebulización Pediátrica';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001494';$product->name = 'Tubo Endotraqueal C/Balón 7,5mm ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100002314';$product->name = 'Salbutamol 0.5% Solución para Nebulización 20mL';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100002679';$product->name = 'Apósito Gasa + Algodón 10cm x 10cm';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001322';$product->name = 'Sonda de Aspiración con Control Succión 12FR ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1000002951';$product->name = 'Branula 24G x 19mm ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1617871';$product->name = 'Mascarilla Laringea #3.0 ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1649132';$product->name = 'Mascarilla Laringea #4.0 ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1646686';$product->name = 'Mascarilla Laringea #5.0 ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '10000100019';$product->name = 'Mascarilla Venturi con 6 Dilutores Pediátrica';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1079078000536';$product->name = 'Mascarilla Oxigeno Alta Concentración C/Reservorio Pediátrica';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7806130005327';$product->name = 'Mascarilla 3P con Tiras x 50 UD';$product->unit = 'CJ';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000937';$product->name = 'Llave de Tres Pasos ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100002882';$product->name = 'Venda Gasa Elásticada 10cm x 4m ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000147';$product->name = 'Venda Apósito Gasa / Algodón 10cm x 1,5m';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000990';$product->name = 'Mascarilla Nebulización Adulto';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000749';$product->name = 'Guante P/Exámen de Latex Talla L ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000748';$product->name = 'Guante P/Exámen de Latex Talla S ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000992';$product->name = 'Mascarilla Venturi Adulto';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1000014571';$product->name = 'Torula de Algodón 0,5g x 100 UD';$product->unit = 'BS';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001493';$product->name = 'Tubo Endotraqueal C/Balón 7,0mm ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001426';$product->name = 'Tela Adhesiva Plástica Transparente 5cm x 9m ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001425';$product->name = 'Tela Adhesiva Plástica Transparente 2,5cm x 9m ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000848';$product->name = 'Jeringa Desechable 3mL con Aguja 21G 1 1/2´´ ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001353';$product->name = 'Naricera P/Oxigeno Adulto';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000693';$product->name = 'Furosemida 20mg/2mL Solución Inyectable ';$product->unit = 'AM';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1646690';$product->name = 'Mascarilla Laringea  #1.0 ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1646689';$product->name = 'Mascarilla Laringea #2.0 ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7806130006782';$product->name = 'Venda Elástica 10cm x 4,5m';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001000';$product->name = 'Mascarilla Venturi Pediátrica';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000146';$product->name = 'Apósito Gasa + Algodón 10cm x 20cm ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '60006';$product->name = 'Estilete de Intubación 14 FR ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '11123456789';$product->name = 'Rollo Electrocardiograma Equipo LIFE PACK';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '121234567';$product->name = 'Rollo Electrocardiograma Equipo Zoll ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1597607';$product->name = 'Cánula Mayo #00';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1300129';$product->name = 'Cánula Mayo #0';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1300134';$product->name = 'Cánula Mayo #5';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000998';$product->name = 'Mascarilla P/Oxigeno Pediátrica Con Reservorio';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000056';$product->name = 'Aguja Hipodérmica 21G 1 1/2 ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1252251';$product->name = 'Caja Cortopunzante M';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1252252';$product->name = 'Caja Cortopunzante L';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000760';$product->name = 'Guante Quirúrgico 7 1/2 x 50 Pares';$product->unit = 'CJ';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001308';$product->name = 'Cloruro de Sodio 0,9% Solución Inyectable 500mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000045';$product->name = 'Agua estéril p/inyectables 5mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '10707387582200';$product->name = 'Electrodo de Monitorización x 50 Unidades';$product->unit = 'BS';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001424';$product->name = 'Tela Adhesiva Microporosa 5cm x 9m';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000295';$product->name = 'Branula IV 24G ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000750';$product->name = 'Guante P/Exámen de Latex Talla M x 100 Unidades';$product->unit = 'CJ';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000178';$product->name = 'Baja Lengua de Madera Desechable ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000097';$product->name = 'Algodón Hidrófilo Prensado Premium x 1 Kg';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000649';$product->name = 'Flumazenilo 0,5mg/5mL Solución Inyectable ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '123456';$product->name = 'SpO2 Sensor ECG';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '123456';$product->name = 'Cable 12 Derivaciones ECG Zoll';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000760';$product->name = 'Guante Quirúrgico 7 x 50 Pares';$product->unit = 'CJ';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001321';$product->name = 'Sonda de Aspiración con Control Succión 10FR ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001355';$product->name = 'Naricera P/Oxigeno Pediátrica';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1000001471';$product->name = 'Apósito gasa algodón 10cm x 100cm';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000993';$product->name = 'Mascarilla P/Oxigeno Adulto Con Reservorio';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000993';$product->name = 'Mascarilla Oxigeno Alta Concentración C/Reservorio Adulto';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '104034342082123';$product->name = 'Sonda de Aspiración Sistema Cerrado N°6 x 31cm ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '43441';$product->name = 'Collar Cervical Adulto';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '43442';$product->name = 'Collar Cervical Pediátrico';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000772';$product->name = 'Hidrocortisona 100mg Liofilizado para solución inyectable ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7800061025102';$product->name = 'Amiodarona Clorhidrato 150mg/3mL Solución Inyectable';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7223150';$product->name = 'Yankauer c/control vacio ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001340';$product->name = 'Sonda Levin Nasogástrica 14 FR ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '123456';$product->name = 'Estilete de Intubación 10 FR  OD 3.3mm';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '17800062003595';$product->name = 'Glucosa (dextrosa) 10% de 250mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001423';$product->name = 'Tela Adhesiva Microporosa 2.5cm x 9m ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000701';$product->name = 'Gasa 5x50 centímetros ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000183';$product->name = 'Bata de Procedimiento Talla L ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000170';$product->name = 'Atropina Sulfato 1mg/1mL Solución Inyectable ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001020';$product->name = 'Metamizol Sódico 1g/2mL Solución Inyectable ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '123456';$product->name = 'Mascarilla de Protección N°95 ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '123456';$product->name = 'Delantal Clínico Plástico';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000306';$product->name = 'Captopril 25mg x 30 Comprimidos (SAMU)';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001320';$product->name = 'Sonda de Aspiración con Control Succión 8FR ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100002919';$product->name = 'Cloruro de Sodio 0,9% Solución Inyectable 100mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1000002931';$product->name = 'Branula IV 20G x 1 1/4 x 32mm';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '123456';$product->name = 'Cubre Calzado Azul ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '18045';$product->name = 'Rollo Electrocardiograma Clinicon 80mm x 20m';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001298';$product->name = 'Bicarbonato de Sodio 2/3 molar Solución Inyectable x 250mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000729';$product->name = 'Glucosa (dextrosa) 10% de 500mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001313';$product->name = 'Ringer Lactato de 500mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '987654';$product->name = 'Glucosalino Isotónico Dextrosa al 2.5% en Solución Salina de 500mL';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7806130006980';$product->name = 'Termòmetro Clìnico Digital Con Alarma';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7800086778106';$product->name = 'Suxametonio Cloruro 100mg Liofilizado para Solución Inyectable 1 FA';$product->unit = 'FA';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000559';$product->name = 'Epinefrina 1mg/1mL Solución Inyectable ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '14026704341686';$product->name = 'Tubo Endotraqueal C/Balón 3,5mm';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '963258369';$product->name = 'Guante Vinilo Talla S x 100 Unidades';$product->unit = 'CJ';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1000005731';$product->name = 'Equipo Macrogoteo 15 a 20 gotas/mL Luer Lock';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7800062002673';$product->name = 'Sulfato de Magnesio 25% Solución Inyectable ';$product->unit = 'AM';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7800061105101';$product->name = 'Clorfenamina Maleato 10mg/mL Solución Inyectable ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '422216042239';$product->name = 'Filtro Traqueostomía Intersurgical Adulto c/puerto para Capnografía';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '17800062004059';$product->name = 'Lanatósido C 0,4mg/2mL Solución Inyectable ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7809605500150';$product->name = 'Ipratropio Bromuro Solución para inhalación 0,025% 20 mL.';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '27800062000324';$product->name = 'Verapamilo Clorhidrato Solución Inyectable 5mg/2mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000567';$product->name = 'Equipo Infusión Soluciones Microgoteo 60 gotas/mL Luer Lock';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '17800062003144';$product->name = 'Dopamina Clorhidrato Solución Inyectable 200mg/5mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '17800062003281';$product->name = 'Nitroglicerina Solución Inyectable 50mg/10mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '22212511';$product->name = 'Sonda Levin Nasogástrica 08 FR ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7891463002389';$product->name = 'Jeringa Hipodérmica 5mL con aguja 21G x 1 1/2 Luer Slip';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7800061001212';$product->name = 'Betametasona Sodio Fosfato 4mg/1mL Solución IV-IM ampollas';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '22236320';$product->name = 'Sonda Foley FR°18 5-15cc 2 vías';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7800061001007';$product->name = 'Dexametasona 4mg/mL Solución Inyectable';$product->unit = 'AM';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '4250105607888';$product->name = 'Estilete de Intubación 4 - 4,5mm';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '20884522004074';$product->name = 'Estilete de Intubación FR 6 (2,0mm)';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7806130010321';$product->name = 'Set Administración Soluciones con Bureta 60 gotas / 1mL x 100mL';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '36548523574';$product->name = 'Jeringa Luer Lock 10mL con Aguja 21G 1 1/2´´ estéril';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7800061001359';$product->name = 'Pargeverina Clorhidrato 5mg/1mL Solución Inyectable ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '121212';$product->name = 'Tijera de extricación';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7707236127510';$product->name = 'Hidrocortisona 500 mg polvo liofilizado para solución inyectable i.m./i.v. en ampolla';$product->unit = 'AM';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001063';$product->name = 'Naloxona Clorhidrato 0,4mg/mL Solución Inyectable ';$product->unit = 'AM';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7800062000587';$product->name = 'Glucosa (dextrosa) 30% de 500mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000279';$product->name = 'Gluconato de Calcio 10% x 10 mL';$product->unit = 'AM';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7800086800005';$product->name = 'Fenitoína Sódica 250mg/5mL Solución Inyectable ';$product->unit = 'AM';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7800062001792';$product->name = 'Agua Bidestilada 500mL';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '847946001469';$product->name = 'Parche Zoll Pediátrico';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '847946016456';$product->name = 'Parche Zoll Adulto';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100002179';$product->name = 'Cloruro de Calcio 10% 10 mL ';$product->unit = 'AM';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1560401';$product->name = 'Resucitador Manual AMBU Adulto Modelo OVAL';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '22204770';$product->name = 'Cánula Mayo #2';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '22204780';$product->name = 'Cánula Mayo #3';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '42272016';$product->name = 'Cánula Mayo #4';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7800062003700';$product->name = 'Glucosa (dextrosa) 5% de 500mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '6944932704466';$product->name = 'Sonda de Aspiración con Control Succión 8FR  ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7800063315775';$product->name = 'Ácido Acetilsalicílico 500 mg ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '201239202512';$product->name = 'Trocar de Osteoclisis Automático Adulto B.I.G';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '202134202504';$product->name = 'Trocar de Osteoclisis Automático Pediátrico B.I.G';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '16944932700212';$product->name = 'Tubo Endotraqueal S/Balón 2.5mm ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '16944932700076';$product->name = 'Tubo Endotraqueal C/Balón 5mm ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '110091806';$product->name = 'Tubo Endotraqueal C/Balón 8.0mm ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '124250022';$product->name = 'Sonda de Aspiración con Control Succión 6FR';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '310211';$product->name = 'Hojas de Bisturí Acero Estériles #11 ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000918';$product->name = 'Lidocaina 2% 5mL ';$product->unit = 'AM';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '42272001';$product->name = 'Laringoscopio Miller';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '42272002';$product->name = 'Laringoscopio Macintosh';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '10011000';$product->name = 'Venda genero';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '7804635810163';$product->name = 'Jeringa Luer Lock 5mL con Aguja 21G 1 1/2´´ estéril ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001310';$product->name = 'Cloruro de sodio 0,9% 20mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000047';$product->name = 'Agua esteril para inyectables 10mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100002561';$product->name = 'Cloruro de Sodio 10% 10mL';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000146';$product->name = 'Aposito de gasa + Algodón 7x20cm ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000152';$product->name = 'Aposito de gasa + algodon 40x40 cm ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100002758';$product->name = 'Gasa 5 X 68 A 72 CM 4 Pliegues Estéril';$product->unit = 'BL';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '9200012085';$product->name = 'Tubo endotraqueal c/bal 8,5';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '9200012060';$product->name = 'Tubo endotraqueal c/bal 6,0';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '919001030';$product->name = 'Tubo endotraqueal s/bal 3,0';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '919001055';$product->name = 'Tubo endotraqueal s/bal 5,5';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '919001035';$product->name = 'Tubo endotraqueal s/bal 3,5';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1266108';$product->name = 'Aguja Hipodérmica Estéril 19G x 1 1/2 ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '240228';$product->name = 'Tubo Endotraqueal s/bal 2,0';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '700083';$product->name = 'Tubo endotraqueal c/bal 5,5';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '171117';$product->name = 'Canula Mayo #1';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '700281';$product->name = 'Tubo Endotraqueal s/bal 6,0';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '27000109';$product->name = 'Tubo endotraqueal c/bal 6,5';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1531313';$product->name = 'Sonda de Aspiración 18FR';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1531314';$product->name = 'Sonda de Aspiración 14FR';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '2700298';$product->name = 'Tubo Endotraqueal s/bal 6,5';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '42181709';$product->name = 'Rollo térmico Zoll 80mm cuadrícula Rolls';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '42151601';$product->name = 'Gasa estéril 5x5 cm, no tejida, 4 pliegues ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001306';$product->name = 'Cloruro de Sodio 0.9% 250 mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000726';$product->name = 'Glucosa (dextrosa) 5% de 1000mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '16944932700243';$product->name = 'Tubo endotraqueal s/bal 4.0';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '16944932700244';$product->name = 'Tubo endotraqueal s/bal 4.5';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '42272301';$product->name = 'Resucitador Manual Desechable Pediátrico';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '920012045';$product->name = 'Tubo endotraqueal c/bal 4,5 ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100001458';$product->name = 'Tórula algodón 3,5g x100 unidades';$product->unit = 'BS';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '5000105740';$product->name = 'Alcohol Gel Tópico 70% x 340 mL';$product->unit = 'FC';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '104382';$product->name = 'Cloruro de Sodio 0.9% 10 mL ';$product->unit = 'AM';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000722';$product->name = 'Glucosa (dextrosa) 5% de 250mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000626';$product->name = 'Fenoterol/Ipratropio 0,5/0,25 mg/mL x 20mL';$product->unit = 'FC';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1100918066';$product->name = 'Tubo endotraqueal c/bal 8,0';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '178624073';$product->name = 'PROPANOLOL 1MG/1ML ';$product->unit = 'AM';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100140';$product->name = 'Tubo endotraqueal c/bal 4,0 ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '532279';$product->name = 'Cloruro de Sodio 0,9% 1000ml ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '42291607';$product->name = 'Pinza Kelly curva';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '42291608';$product->name = 'Pinza Magill 20 cm';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1300128';$product->name = 'Canula mayo #000';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '500015429';$product->name = 'Parche curita redondo 22mm x100';$product->unit = 'CJ';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1612008';$product->name = 'Aguja espinal punta lápiz 25G x 90 mm';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1000001472';$product->name = 'Venda Gasa Elásticada 12cm x 4m ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = 'fy2009035';$product->name = 'Tubo endotraqueal c/bal 9mm';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000038';$product->name = 'Adenosina 6mg/2mL ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '222136652';$product->name = 'Tubo Endotraqueal 3.0 C/Balón';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '100000287';$product->name = 'Branula 14G x 45mm ';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '315623';$product->name = 'Jeringa 60 mL con Pivote (unidad)';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1212121';$product->name = 'Tubo Endotraqueal C/Bal FR 5.0';$product->unit = 'UD';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '1';$product->name = 'MORFINA 10 MG 2 ML';$product->unit = 'AM ';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '2';$product->name = 'MIDAZOLAM 15 MG 3 ML';$product->unit = 'AM';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();
        $product = new Product();$product->barcode = '13';$product->name = 'DIAZEPAM 10 MG 2 ML ';$product->unit = 'AM ';$product->stock = 0;$product->pharmacy_id = 6;$product->category_id = 2;$product->program_id = 9;$product->save();

    }
}
