<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Notification;
use App\Notifications\SystemNotification;

class MailProrrogaContratacion2024 extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'command:prorroga-contratacion';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $array = [];
        // $array[0]['nombre'] = 'Alvaro';
        // $array[0]['email'] = 'alvaro.torres@redsalud.gob.cl';

        // $array[1]['nombre'] = 'Jorge';
        // $array[1]['email'] = 'jorge.mirandal@redsalud.gob.cl';

        // $array[2]['nombre'] = 'Esteban';
        // $array[2]['email'] = 'esteban.miranda@redsalud.gob.cl';

        // $array[0]['nombre'] = 'SERGIO TUDELA ';$array[0]['email'] = 'sergio.tudela@redsalud.gob.cl';
        // $array[1]['nombre'] = 'ESTEBAN ROJAS ';$array[1]['email'] = 'esteban.rojasg@redsalud.gob.cl';

        // $array[0]['nombre'] = 'ABARZUA CONSTANZO JAIME ';$array[0]['email'] = 'JAIME.ABARZUA@REDSALUD.GOV.CL';
        // $array[1]['nombre'] = 'ADONIS VALENCIA CAROLINA ';$array[1]['email'] = 'carolina.adonis@redsalud.gob.cl';
        // $array[2]['nombre'] = 'AELOISA AZABACHE MARCELO ';$array[2]['email'] = 'MARCELO.AELOISA@REDSALUD.GOV.CL';
        // $array[3]['nombre'] = 'AGUIRRE FUNEZ ALEJANDRA ';$array[3]['email'] = 'alejandra.aguirre@redsalud.gov.cl';
        // $array[4]['nombre'] = 'ANCH MONDACA SAN YUN ';$array[4]['email'] = 'SANYUN.ANCH@REDSALUD.GOB.CL';
        // $array[5]['nombre'] = 'ARAPIO SANDOVAL MARIBEL ';$array[5]['email'] = 'MARIBEL.ARAPIO@REDSALUD.GOV.CL';
        // $array[6]['nombre'] = 'ARAYA CHACON GILDA ';$array[6]['email'] = 'GILDA.ARAYA.CHACON@GMAIL.COM';
        // $array[7]['nombre'] = 'AVALOS PARRA SHEYLA ';$array[7]['email'] = 'SHEYLAA@GMAIL.COM';
        // $array[8]['nombre'] = 'BAEZA GUERRA JULIO ';$array[8]['email'] = 'JULIOBAEZAGUERRA@GMAIL.COM';
        // $array[9]['nombre'] = 'BARRAZA CARVAJAL LUIS ';$array[9]['email'] = 'CLAUDIO.BARRAZA@REDSALUD.GOV.CL';
        // $array[10]['nombre'] = 'BERENGUELA ALVAREZ PATRICIO';$array[10]['email'] = 'patricio.berenguela@samutarapaca.cl';
        // $array[11]['nombre'] = 'BERMEDO GONZALEZ CARLA';$array[11]['email'] = 'CARLABERMEDO@GMAIL.COM';
        // $array[12]['nombre'] = 'BERMUDEZ LAZCANO JONNATAN ';$array[12]['email'] = 'PSICOBERMUDEZ@GMAIL.COM';
        // $array[13]['nombre'] = 'CACERES TICONA ALEX ';$array[13]['email'] = 'alexorlandocaceres@gmail.com';
        // $array[14]['nombre'] = 'CACERES TICONA MARGARITA ';$array[14]['email'] = 'margarita.cacerest@redsalud.gob.cl';
        // $array[15]['nombre'] = 'CALISAYA ILAJA DANIELA ';$array[15]['email'] = 'DANICALISAYA@GMAIL.COM';
        // $array[16]['nombre'] = 'CARONNA VILLALOBOS CLAUDIA ';$array[16]['email'] = 'claudia.caronna@redsalud.gov.cl';
        // $array[17]['nombre'] = 'CARRASCO GATICA MACARENA ';$array[17]['email'] = 'MACARENA.CARRASCOG@REDSALUD.GOV.CL';
        // $array[18]['nombre'] = 'CARRASCO RAMIREZ MARIANO ';$array[18]['email'] = 'MARIANO.CARRASCO.R@GMAIL.COM';
        // $array[19]['nombre'] = 'CASTILLO CARDENAS PIERO ';$array[19]['email'] = 'PIEROCASTILLOCARDENAS6@GMAIL.COM';
        // $array[20]['nombre'] = 'CASTRO HERRADA CAROLINA ';$array[20]['email'] = 'CAROLINA.CASTROH@REDSALUD.GOV.CL';
        // $array[21]['nombre'] = 'CHANDIA DEVIA MARITTE ';$array[21]['email'] = 'MARITTE.CHANDIA@GMAIL.COM';
        // $array[22]['nombre'] = 'CLAROS AYALA ESTEFANIE ';$array[22]['email'] = 'ESTEFANIE.CLAROS@REDSALUD.GOB.CL';
        // $array[23]['nombre'] = 'COLLAO CARVAJAL CARLOS ';$array[23]['email'] = 'carlos.collao@redsalud.gov.cl';
        // $array[24]['nombre'] = 'CONTRERAS ARAYA PAMELA ';$array[24]['email'] = 'PCONTRERAS430@GMAIL.COM';
        // $array[25]['nombre'] = 'CORDANO TEJEDA JORGE ';$array[25]['email'] = 'JLCORDANO@YAHOO.COM';
        // $array[26]['nombre'] = 'CORDOVA MIRANDA GILBERTO ';$array[26]['email'] = 'GILBERTOCORDOVA.M@GMAIL.COM';
        // $array[27]['nombre'] = 'CORRALES GAMBOA BALENA ';$array[27]['email'] = 'BALENA.KIRIN@GMAIL.COM';
        // $array[28]['nombre'] = 'CORTES CACERES CYNTHIA';$array[28]['email'] = 'CYNTHIA.CORTES@REDSALUD.GOV.CL';
        // $array[29]['nombre'] = 'CORTES HIDALGO LUIS RODRIGO';$array[29]['email'] = 'LUISRODRIGO73@HOTMAIL.COM';
        // $array[30]['nombre'] = 'CORTES MANCILLA CAROLIN';$array[30]['email'] = 'CBCM555@GMAIL.COM';
        // $array[31]['nombre'] = 'CRAIG DEROUT ANGIE';$array[31]['email'] = 'angie.craig@redsalud.gov.cl';
        // $array[32]['nombre'] = 'CRIGNOLA TOLEDO ALEJANDRA';$array[32]['email'] = 'ALEJANDRA.CRIGNOLA@REDSALUD.GOB.CL';
        // $array[33]['nombre'] = 'CURIN TAPIA DOMINGO';$array[33]['email'] = 'DOMINGO.CURIN@REDSALUD.GOV.CL';
        // $array[34]['nombre'] = 'CURUTCHET BUSTAMANTE MARGARITA';$array[34]['email'] = 'MAGYCURUTCHET@GMAIL.COM';
        // $array[35]['nombre'] = 'DIAZ RAMIREZ KAREN ';$array[35]['email'] = 'karen.adr@hotmail.com';
        // $array[36]['nombre'] = 'DONOSO CARRERA JOSE ';$array[36]['email'] = 'JOSE.DONOSOC@REDSALUD.GOB.CL';
        // $array[37]['nombre'] = 'DONOSO PASTEN DANNY ';$array[37]['email'] = 'DAHERMY_@HOTMAIL.COM';
        // $array[38]['nombre'] = 'ESCUDERO CARVAJAL HECTOR ';$array[38]['email'] = 'alejandroescudero5@hotmail.com';
        // $array[39]['nombre'] = 'ESTAY SANCHEZ PRISCILA ';$array[39]['email'] = 'PRISCILA.ESTAY@REDSALUD.GOB.CL';
        // $array[40]['nombre'] = 'FERNANDEZ ARAYA CRISTIAN ';$array[40]['email'] = 'cristianfernandez031@gmail.com';
        // $array[41]['nombre'] = 'FERNANDEZ HERRERA BERTA ';$array[41]['email'] = 'berta.fernandezh@redsalud.gov.cl';
        // $array[42]['nombre'] = 'FLORES GONZALEZ BASILIO ';$array[42]['email'] = 'BASHOFLORES@GMAIL.COM';
        // $array[43]['nombre'] = 'FUENTES ORTEGA CLAUDIO ';$array[43]['email'] = 'CLAUDIOFUENTES14@GMAIL.COM';
        // $array[44]['nombre'] = 'GACITUA RUBIO MARCIAL ';$array[44]['email'] = 'GACITUAMARCIAL@GMAIL.COM';
        // $array[45]['nombre'] = 'GALLEGUILLOS GONZALEZ YAZMIN ';$array[45]['email'] = 'YAZMIN.GALLEGUILLOS@REDSALUD.GOB.CL';
        // $array[46]['nombre'] = 'GARIN JORQUERA ROMINA ';$array[46]['email'] = 'ROMINA.GARIN@REDSALUD.GOB.CL';
        // $array[47]['nombre'] = 'GATICA OLEA VALENTINA';$array[47]['email'] = 'VALEGATICAOLEA@GMAIL.COM';
        // $array[48]['nombre'] = 'GIMENEZ GALLEGOS NATALIA ';$array[48]['email'] = 'NATYGIMENEZ@GMAIL.COM';
        // $array[49]['nombre'] = 'GODOY DIAZ ROBERTO ';$array[49]['email'] = 'NATYGIMENEZ@GMAIL.COM';
        // $array[50]['nombre'] = 'GOMEZ CHAVEZ GIOVANNA';$array[50]['email'] = 'giovy.2101@gmail.com';
        // $array[51]['nombre'] = 'GONZALEZ GARCIA LETICIA';$array[51]['email'] = 'LETGONZA@GMAIL.COM';
        // $array[52]['nombre'] = 'GONZALEZ MORALES OMAYRA ';$array[52]['email'] = 'OMAYRABELENGOZALEZ@GMAIL.COM';
        // $array[53]['nombre'] = 'GUTIERREZ REYES DANIEL ';$array[53]['email'] = 'DANIELAGUTIERREZREYES96@GMAIL.COM';
        // $array[54]['nombre'] = 'HANS FUENTES INGRID ';$array[54]['email'] = 'INHANS@LIVE.COM';
        // $array[55]['nombre'] = 'HENRIQUEZ ELGUEDA FRANCIS ';$array[55]['email'] = 'francis.henriquez@live.com';
        // $array[56]['nombre'] = 'HENRIQUEZ OLIVARES CARMEN';$array[56]['email'] = 'CARMEN.HENRIQUEZ@REDSALUD.GOV.CL';
        // $array[57]['nombre'] = 'HEREDIA CEBALLOS JIMENA';$array[57]['email'] = 'jimena.herediac@gmail.com';
        // $array[58]['nombre'] = 'HUENUPIL LLANQUINAO LUZ';$array[58]['email'] = 'LUZ.HUENUPIL@REDSALUD.GOV.CL';
        // $array[59]['nombre'] = 'INOSTROZA ROJAS ROSEMARIE';$array[59]['email'] = 'ROSEINOSTROZA@HOTMAIL.COM';
        // $array[60]['nombre'] = 'JOFRE ROJAS DIANA';$array[60]['email'] = 'jofrerojas@gmail.com';
        // $array[61]['nombre'] = 'KUWAHARA ABALLAY YUKIKO ';$array[61]['email'] = 'YUKIKO.KUWAHARA@REDSALUD.GOV.CL';
        // $array[62]['nombre'] = 'LOPEZ MENESES ESTHER ';$array[62]['email'] = 'ELOPEZMENESES@HOTMAIL.COM';
        // $array[63]['nombre'] = 'LUPA HUANCA ALVARO ';$array[63]['email'] = 'ALVARO.LUPA@GMAIL.COM';
        // $array[64]['nombre'] = 'MADARIAGA ARAYA NICOLE ';$array[64]['email'] = 'N.MADARIAGA.A@GMAIL.COM';
        // $array[65]['nombre'] = 'MAMANI ROJAS ORLANDO ';$array[65]['email'] = 'PS.ORLANDOMAMANI@GMAIL.COM';
        // $array[66]['nombre'] = 'MARABOLI CALDERON NINA';$array[66]['email'] = 'nina.maraboli1977@gmail.com';
        // $array[67]['nombre'] = 'MEDINA HENRIQUEZ PABLO ';$array[67]['email'] = 'PABLO.MEDINA@REDSALUD.GOV.CL';
        // $array[68]['nombre'] = 'MELIS TORREJON MICHAEL ';$array[68]['email'] = 'michael.melis@redsalud.gov.cl';
        // $array[69]['nombre'] = 'MENENDEZ QUIROGA GELDY ';$array[69]['email'] = 'GELDY.MENENDEZ@REDSALUD.GOV.CL';
        // $array[70]['nombre'] = 'MOLINA SAN MARTIN TATIANA ';$array[70]['email'] = 'tatiana.molina@redsalud.gob.cl';
        // $array[71]['nombre'] = 'MONDACA FARIAS MARIA ';$array[71]['email'] = 'GRACIELA.MONDACA@REDSALUD.GOV.CL';
        // $array[72]['nombre'] = 'MONDACA MOLINA MATEO ';$array[72]['email'] = 'MATEO.MONDACA.MOLINA@GMAIL.COM';
        // $array[73]['nombre'] = 'MONTECINOS VALLEJOS MARIA ';$array[73]['email'] = 'MARIAJOSEMONTECINOSVALLEJOS@GMAIL.COM';
        // $array[74]['nombre'] = 'MORALES GARCIA MARCELO ';$array[74]['email'] = 'MARCEMOR690@GMAIL.COM';
        // $array[75]['nombre'] = 'MORALES ROBLES CAROLINA ';$array[75]['email'] = 'CARO.STEPHANY@GMAIL.COM';
        // $array[76]['nombre'] = 'MORGADO LEDEZMA MARCO ';$array[76]['email'] = 'marco.morgado@redsalud.gob.cl';
        // $array[77]['nombre'] = 'MUENA BUGUEÑO LUIS ';$array[77]['email'] = 'LMUENA@GMAIL.COM';
        // $array[78]['nombre'] = 'MUJICA LOPEZ ANA MARIA';$array[78]['email'] = 'ANA.MUJICA@REDSALUD.GOV.CL';
        // $array[79]['nombre'] = 'MUNIZAGA CORNEJO NICOLE ';$array[79]['email'] = 'N.MUNIZAGA.TO@GMAIL.COM';
        // $array[80]['nombre'] = 'NARBONA ROCUANT MARIA ';$array[80]['email'] = 'mariasoledad.narbona@redsalud.gob.cl';
        // $array[81]['nombre'] = 'NAVEA SOTO GABRIEL ';$array[81]['email'] = 'GABRIEL.NAVEA@REDSALUD.GOB.CL';
        // $array[82]['nombre'] = 'NIÑO SAAVEDRA DIANA ';$array[82]['email'] = 'DIANA.ANS@GMAIL.COM';
        // $array[83]['nombre'] = 'NORIEGA OROZ CRISTINA ';$array[83]['email'] = 'cristina.noriega@redsalud.gob.cl';
        // $array[84]['nombre'] = 'OYARCE TORRES NATALIA ';$array[84]['email'] = 'NATALIA.OYARCE.TORRES@GMAIL.COM';
        // $array[85]['nombre'] = 'OYARCE VALDIVIA OMAR ';$array[85]['email'] = 'OMAR.OYARCE.VALDIVIA@GMAIL.COM';
        // $array[86]['nombre'] = 'PARADA SOTO MACARENA ';$array[86]['email'] = 'PARADA.MACARENA@GMAIL.COM';
        // $array[87]['nombre'] = 'PASTEN CHAMBE TERESA';$array[87]['email'] = 'TEPASTEN@GMAIL.COM';
        // $array[88]['nombre'] = 'PEREZ REBOLLEDO CAROLINA ';$array[88]['email'] = 'CAROLINA.PEREZ@REDSALUD.GOV.CL';
        // $array[89]['nombre'] = 'PFEIFFER FLORES MICHELE ';$array[89]['email'] = 'MICHELE.PFEIFFER@REDSALUD.GOB.CL';
        // $array[90]['nombre'] = 'POBLETE FUENTES SEBASTIAN ';$array[90]['email'] = 'sebastian.poblete@redsalud.gob.cl';
        // $array[91]['nombre'] = 'POL JACOME HAYLEEN ';$array[91]['email'] = 'HAYLEN.POL@GMAIL.COM';
        // $array[92]['nombre'] = 'POZO CABALLERO NATALIA ';$array[92]['email'] = 'NPC.CABALLERO@GMAIL.COM';
        // $array[93]['nombre'] = 'QUEZADA LAGOS PAULA';$array[93]['email'] = 'PAULA.QUEZADA@REDSALUD.GOB.CL';
        // $array[94]['nombre'] = 'REVECO GARCIA DANIELA ';$array[94]['email'] = 'drevecog@gmail.com';
        // $array[95]['nombre'] = 'REYES MUÑOZ DEYANIRA ';$array[95]['email'] = 'DEYANIRA.REYESM@GMAIL.COM';
        // $array[96]['nombre'] = 'RODRIGUEZ MONTES ELISABETH';$array[96]['email'] = 'elizabethrodriguezmontes@gmail.com';
        // $array[97]['nombre'] = 'ROMERO ROMERO MARIELA ';$array[97]['email'] = 'GRUPALREUNION42@GMAIL.COM';
        // $array[98]['nombre'] = 'SAEZ ZARATE GONZALO ';$array[98]['email'] = 'GONZALO.SAEZ@REDSALUD.GOB.CL';
        // $array[99]['nombre'] = 'SALGADO ANONI MARIA ';$array[99]['email'] = 'MCSA65@GMAIL.COM';
        // $array[100]['nombre'] = 'SALGADO MORENO PRISILLA ';$array[100]['email'] = 'PRISILLA.SALGADO@GMAIL.COM';
        // $array[101]['nombre'] = 'SANTANDER OLCAY MARIA ';$array[101]['email'] = 'MITAI_9@HOTMAIL.COM';
        // $array[102]['nombre'] = 'SARMIENTO GANDARILLAS JORGE ';$array[102]['email'] = 'SARMIENTOGANDARILLAS@GMAIL.COM';
        // $array[103]['nombre'] = 'SEPULVEDA GUTIERREZ CLAUDIA ';$array[103]['email'] = 'DITASG@GMAIL.COM';
        // $array[104]['nombre'] = 'SILVA DIAZ LORETO ';$array[104]['email'] = 'LSILVADIAZ@REDSALUD.GOB.CL';
        // $array[105]['nombre'] = 'SILVA GONZALEZ JOSE ';$array[105]['email'] = 'JOSE.SGONZALEZ@REDSALUD.GOB.CL';
        // $array[106]['nombre'] = 'SOBREVILLA CHANG PATRICIO ';$array[106]['email'] = 'PATRICIO.SOBREVILLA@REDSALUD.GOV.CL';
        // $array[107]['nombre'] = 'SOTO FUENTES MIREYA';$array[107]['email'] = 'MIREYA.SOTOF@REDSALUD.GOV.CL';
        // $array[108]['nombre'] = 'TAPIA ROSELLO PAULA';$array[108]['email'] = 'tapiarosello@gmail.com';
        // $array[109]['nombre'] = 'TORRES CAMPILLAY CARLOS ';$array[109]['email'] = 'CMANUELTC@GMAIL.COM';
        // $array[110]['nombre'] = 'TORRES GUZMAN ALEJANDRA ';$array[110]['email'] = 'ALETORRESG.81@GMAIL.COM';
        // $array[111]['nombre'] = 'TUDELA FARFAN SERGIO ';$array[111]['email'] = 'STUDELAF@GMAIL.COM';
        // $array[112]['nombre'] = 'VALDES SOLAR DEBORA ';$array[112]['email'] = 'DEBORAVALDES.S@GMAIL.COM';
        // $array[113]['nombre'] = 'VARGAS ARAYA MIGUEL ';$array[113]['email'] = 'MIGUEL.VARGAS.A@REDSALUD.GOB.CL';
        // $array[114]['nombre'] = 'VASQUEZ GUACTE IRENE';$array[114]['email'] = 'IRENE.VASQUEZ@REDSALUD.GOB.CL';
        // $array[115]['nombre'] = 'VEGA GALLARDO SHALOM ';$array[115]['email'] = 'SHALOM.BELEN@GMAIL.COM';
        // $array[116]['nombre'] = 'VERGARA OSORIO JOSE';$array[116]['email'] = 'JVERGARAOSORIO@GMAIL.COM';
        // $array[117]['nombre'] = 'VILCHES ZAMBRANO MARIA ';$array[117]['email'] = 'ME.VILCHESZAMBRANO@GMAIL.COM';
        // $array[118]['nombre'] = 'ZAMORA NAVARRO CARLA ';$array[118]['email'] = 'ZAMORA.CARLA@REDSALUD.GOB.CL';
        // $array[119]['nombre'] = 'ZUÑIGA ASTUDILLO MARIA ';$array[119]['email'] = 'MARIA.ZUNIGA@REDSALUD.GOV.CL';
        // $array[120]['nombre'] = 'ZUÑIGA REYES VIVIANA ';$array[120]['email'] = 'VIVIZUNIGAREYES.VZR@GMAIL.COM';
        // $array[121]['nombre'] = 'AEDO ARAYA YESSICA ';$array[121]['email'] = 'YESSIKAEDO.A@GMAIL.COM';
        // $array[122]['nombre'] = 'ALVAREZ PAILLACAN JUDITH ';$array[122]['email'] = 'Judith.alvarez@redsalud.gob.cl';
        // $array[123]['nombre'] = 'AMARO CAQUEO CAROLINA ';$array[123]['email'] = 'CAROLINAAMARO21@GMAIL.COM';
        // $array[124]['nombre'] = 'AMPUERO CONTRERAS KATHERINE';$array[124]['email'] = 'KATHERINE.AMPUERO.C@GMAIL.COM';
        // $array[125]['nombre'] = 'ARAYA COSSIO FABRICCIO ';$array[125]['email'] = 'FARCO_01_@HOTMAIL.COM';
        // $array[126]['nombre'] = 'ARCE WEBER NELSON ';$array[126]['email'] = 'NELSON.ARCE.WEBER@GMAIL.COM';
        // $array[127]['nombre'] = 'ARIAS HERRERA SANDRA ';$array[127]['email'] = 'SHERRERAARIAS00@GMAIL.COM';
        // $array[128]['nombre'] = 'BASCUÑAN BASCUÑAN VALESKA';$array[128]['email'] = 'VALESKA.BASCUNAN@GMAIL.COM';
        // $array[129]['nombre'] = 'BRAVO ARAVENA ROSSANA ';$array[129]['email'] = 'RBRAVOARAVENA@GMAIL.COM';
        // $array[130]['nombre'] = 'CABEZA BUSTAMANTE CHRISTOPHER ';$array[130]['email'] = 'CHRISTOPHER0403@GMAIL.COM';
        // $array[131]['nombre'] = 'CALDERON TOLEDO FRANCO ';$array[131]['email'] = 'franco.calderon@redsalud.gob.cl';
        // $array[132]['nombre'] = 'CAMPUSANO BOLADOS SUSANA';$array[132]['email'] = 'SUSANA.CAMPUSANO.B@GMAIL.COM';
        // $array[133]['nombre'] = 'CAPETILLO SEPULVEDA TAMARA';$array[133]['email'] = 'TAMARACAPETILLOS1@GMAIL.COM';
        // $array[134]['nombre'] = 'CASTAÑEDA MERCADO ANA ';$array[134]['email'] = 'SAMIRAAANA53@GMAIL.COM';
        // $array[135]['nombre'] = 'CIFUENTES OPAZO CARLA ';$array[135]['email'] = 'CARLA.CIFUENTES04@GMAIL.COM';
        // $array[136]['nombre'] = 'COFRE SANHUEZA CATHERIN ';$array[136]['email'] = 'CATHERIN_COFRE.S@HOTMAIL.COM';
        // $array[137]['nombre'] = 'CORRALES SOTO VALERIA ';$array[137]['email'] = 'VALERIA.CORRALES.SOTO@GMAIL.COM';
        // $array[138]['nombre'] = 'DIAZ LABBE CAROLINA';$array[138]['email'] = 'CAROLINADIAZLABBE0826@GMAIL.COM';
        // $array[139]['nombre'] = 'DIEGO ALVINAGORTA BANIA';$array[139]['email'] = 'BANIADIEGO@GMAIL.COM';
        // $array[140]['nombre'] = 'ESTAY HIDALGO VERONICA ';$array[140]['email'] = 'VERUSKA.MEL18@GMAIL.COM';
        // $array[141]['nombre'] = 'FIGUEROA CASTILLO ALVARO';$array[141]['email'] = 'a.figueroa@redsalud.gov.cl';
        // $array[142]['nombre'] = 'FLORES FLORES MARISOL ';$array[142]['email'] = 'FLORES.MARISOL.TENSHBU@GMAIL.COM';
        // $array[143]['nombre'] = 'FORTES CASTRO GERALDINE ';$array[143]['email'] = 'GERALDIN.FORTES.C@GMAIL.COM';
        // $array[144]['nombre'] = 'GALINDO SALAMANCA VARINIA ';$array[144]['email'] = 'variniasalamanca@gmail.com';
        // $array[145]['nombre'] = 'GARVISO PIZARRO JONATHAN';$array[145]['email'] = 'JONATHHAN_CHILE@HOTMAIL.COM';
        // $array[146]['nombre'] = 'JAMETT RIOS LARRY ';$array[146]['email'] = 'LARRYJR2008@HOTMAIL.COM';
        // $array[147]['nombre'] = 'LARA HEVIA BASTIAN ';$array[147]['email'] = 'BASTIAN_STI@HOTMAIL.COM';
        // $array[148]['nombre'] = 'LASTRA CERONI VICTORIA ';$array[148]['email'] = 'VICTORIALASTRACERONI@GMAIL.COM';
        // $array[149]['nombre'] = 'MOLLO TAUCARE ROMINA ';$array[149]['email'] = 'R.MOLLO.87@HOTMAIL.COM';
        // $array[150]['nombre'] = 'MOYA ALIAGA GISSELLA ';$array[150]['email'] = 'GISEL.MOOYA@GMAIL.COM';
        // $array[151]['nombre'] = 'MUÑOZ GARCIA SERGIO ';$array[151]['email'] = 'germanicosergio@gmail.com';
        // $array[152]['nombre'] = 'OLIVARES CORTES MARJORIE ';$array[152]['email'] = 'MARJORIE.OLIVARES.C@GMAIL.COM';
        // $array[153]['nombre'] = 'PASSTENI CELEDON VALERIA';$array[153]['email'] = 'PASSTENI.CELEDON@GMAIL.COM';
        // $array[154]['nombre'] = 'PASTEN IRARRAZABAL DANIEL ';$array[154]['email'] = 'DANIELPASTEN_B4@HOTMAIL.COM';
        // $array[155]['nombre'] = 'PERALTA HERRERA ROSSANA';$array[155]['email'] = 'ROSSANAPH@LIVE.CL';
        // $array[156]['nombre'] = 'PEZOA VALENZUELA JESSICA';$array[156]['email'] = 'JEPEVALE41@GMAIL.COM';
        // $array[157]['nombre'] = 'PORTILLA FIBLA GONZALO ';$array[157]['email'] = 'XALO.PORTILLA@GMAIL.COM';
        // $array[158]['nombre'] = 'PULGAR ROJAS JOSELYN ';$array[158]['email'] = 'BEATIFUL.159@GMAIL.COM';
        // $array[159]['nombre'] = 'RANGEL VARAS KARIME';$array[159]['email'] = 'KARIME.2705@HOTMAIL.COM';
        // $array[160]['nombre'] = 'REYES FAUNDEZ OLIVIA';$array[160]['email'] = 'OLIVITAREYES.OR@GMAIL.COM';
        // $array[161]['nombre'] = 'RIVERA GONZALEZ MARIA ';$array[161]['email'] = 'MARIATERESARG25@GMAIL.COM';
        // $array[162]['nombre'] = 'RIVERA GRAY ROMINA ';$array[162]['email'] = 'KORTIRION58@GMAIL.COM';
        // $array[163]['nombre'] = 'ROBLES CASTILLO CAMILA ';$array[163]['email'] = 'CAMILA19.ROBLES@GMAIL.COM';
        // $array[164]['nombre'] = 'ROCHA ROCO JIONELLY';$array[164]['email'] = 'JROCHA.-@HOTMAIL.COM';
        // $array[165]['nombre'] = 'ROSALES VEAS CONSTANZA ';$array[165]['email'] = 'CONSTANZA.ROSALESVEAS@GMAIL.COM';
        // $array[166]['nombre'] = 'RUZ TELLO NATASHA ';$array[166]['email'] = 'NATTASHAAYLINE@GMAIL.COM';
        // $array[167]['nombre'] = 'SANZANA GONZALEZ DANIELA ';$array[167]['email'] = 'DANIELA.SANZANA.G@GMAIL.COM';
        // $array[168]['nombre'] = 'SARMIENTO PLAZA CARLOS ';$array[168]['email'] = 'CARLOS_S_DH@HOTMAIL.COM';
        // $array[169]['nombre'] = 'TERAN SAAVEDRA JESSICA';$array[169]['email'] = 'JESSICAADRIANA.TERAN@GMAIL.COM';
        // $array[170]['nombre'] = 'VALENZUELA BARRAZA CRISTIAN ';$array[170]['email'] = 'CRISTIAN.CALVITO@GMAIL.COM';
        // $array[171]['nombre'] = 'VEGA LOPEZ XIMENA ';$array[171]['email'] = 'XVEGA@LIVE.CL';
        // $array[172]['nombre'] = 'ZUÑIGA OTEY LORENA ';$array[172]['email'] = 'LOREEZU.01@GMAIL.COM';
        // $array[173]['nombre'] = 'ARAYA VALDEBENITO GIOVANA';$array[173]['email'] = 'GIOVANA.ARAYA@REDSALUD.GOV.CL';
        // $array[174]['nombre'] = 'ARDILES PALACIOS DANITZA ';$array[174]['email'] = 'VANIA.AP2@GMAIL.COM';
        // $array[175]['nombre'] = 'ARELLANO MAMANI ALEJANDRA';$array[175]['email'] = 'ALEJANDRAARELLANO83@GMAIL.COM';
        // $array[176]['nombre'] = 'ASTORGA MAMANI ANA ';$array[176]['email'] = 'ASTORGAANA5@GMAIL.COM';
        // $array[177]['nombre'] = 'AZUA LOPEZ MIGUEL ';$array[177]['email'] = 'MIGUEL.AZUA@REDSALUD.GOV.CL';
        // $array[178]['nombre'] = 'BRUNA BARRAZA CAMILA ';$array[178]['email'] = 'camilabrunabarraza@gmail.com';
        // $array[179]['nombre'] = 'BUGUEÑO CANDIA FRANCISCO';$array[179]['email'] = 'FCOBUGUENOTK@HOTMAIL.COM';
        // $array[180]['nombre'] = 'CAIPA CAQUEO LAURA ';$array[180]['email'] = 'laura.caipa@redsalud.gob.cl';
        // $array[181]['nombre'] = 'CARVAJAL ARANCIBIA LUISA ';$array[181]['email'] = 'LUISA.CARVAJAL.ARAN@GMAIL.COM';
        // $array[182]['nombre'] = 'CARVAJAL PIZARRO MAKARENA ';$array[182]['email'] = 'MAKARENA.CARVAJAL.2@GMAIL.COM';
        // $array[183]['nombre'] = 'CASTILLO BUGUEÑO KAROLAYNE ';$array[183]['email'] = 'KAROLAYNE.CASTILLOB@GMAIL.COM';
        // $array[184]['nombre'] = 'CEBALLOS DERPICH ANDREA ';$array[184]['email'] = 'A.CEBALLOSDERPICH@GMAIL.COM';
        // $array[185]['nombre'] = 'CONTRERAS ESCOBAR KATHERINE';$array[185]['email'] = 'KATHERINE.CONTRERAS@REDSALUD.GOB.CL';
        // $array[186]['nombre'] = 'CORDOVA JOFRE CAMILA ';$array[186]['email'] = 'CAMILA.ISOLETT@GMAIL.COM';
        // $array[187]['nombre'] = 'DIAZ CARRILLO DANIELA ';$array[187]['email'] = 'DANIELA.DIAZC@REDSALUD.GOV.CL';
        // $array[188]['nombre'] = 'DUEÑAS PEÑA NORMA ';$array[188]['email'] = 'N.CONSTANZA64@GMAIL.COM';
        // $array[189]['nombre'] = 'ESPINOZA GOMEZ TAMARA ';$array[189]['email'] = 'TAMARITAPETRIZIA@GMAIL.COM';
        // $array[190]['nombre'] = 'GALAZ ARAYA BLANCA ';$array[190]['email'] = 'NOELIA291287@GMAIL.COM';
        // $array[191]['nombre'] = 'GALDAMEZ MANCILLA EVELYN ';$array[191]['email'] = 'EVELYN.GALDAMEZ@GMAIL.COM';
        // $array[192]['nombre'] = 'GARCIA CASANOVA DUBY';$array[192]['email'] = 'duby.garcia@redsalud.gob.cl';
        // $array[193]['nombre'] = 'GARCIA CHALLAPA NOLFA ';$array[193]['email'] = 'NOLFA.GARCIA.08@GMAIL.COM';
        // $array[194]['nombre'] = 'GODOY VEGA ADELA';$array[194]['email'] = 'mimidaan@gmail.com';
        // $array[195]['nombre'] = 'GOMEZ CAQUISANE PABLO ';$array[195]['email'] = 'PABLO.GOMEZ@REDSALUD.GOV.CL';
        // $array[196]['nombre'] = 'GONZALEZ CRUZ CLAUDIA ';$array[196]['email'] = 'CGONZALEZCRUZ1970@GMAIL.COM';
        // $array[197]['nombre'] = 'GUERRERO TRIGO MARCELA ';$array[197]['email'] = 'MARCELA.GUERRERO@REDSALUD.GOB.CL';
        // $array[198]['nombre'] = 'HAHN ESPINDOLA KURT';$array[198]['email'] = 'HAHNKURTE@GMAIL.COM';
        // $array[199]['nombre'] = 'HERNANDEZ NUÑEZ VIVIANA';$array[199]['email'] = 'VIVIHERNUN@GMAIL.COM';
        // $array[200]['nombre'] = 'JIMENEZ JIMENEZ GEMA';$array[200]['email'] = 'gema.jimenez@redsalud.gov.cl';
        // $array[201]['nombre'] = 'JORQUERA JORQUERA FERNANDO ';$array[201]['email'] = 'TOBRANO.FJ@GMAIL.COM';
        // $array[202]['nombre'] = 'LAGOS NUÑEZ CAMILO ';$array[202]['email'] = 'camilo.lagos@redsalud.gob.cl';
        // $array[203]['nombre'] = 'LEON SOTO FRANCISCA ';$array[203]['email'] = 'FRANCISCALEON452@GMAIL.COM';
        // $array[204]['nombre'] = 'MAMANI CHALLAPA GLORIA ';$array[204]['email'] = 'NELIDAMAMANIJUNIO@GMAIL.COM';
        // $array[205]['nombre'] = 'MELLA LEIVA PATRICIA ';$array[205]['email'] = 'P.MELLA.L@HOTMAIL.COM';
        // $array[206]['nombre'] = 'MOSCOSO TAUCARE CECILIA';$array[206]['email'] = 'cecipilarmoscoso@hotmail.com';
        // $array[207]['nombre'] = 'MOSCOSO TAUCARE MARGARITA';$array[207]['email'] = 'MARGARITA05MOSCOSOC@GMAIL.CL';
        // $array[208]['nombre'] = 'OLIVARES CIFUENTES GUILLERMO';$array[208]['email'] = 'GOC.ASESORIAS@GMAIL.COM';
        // $array[209]['nombre'] = 'ORDENES CUEVAS RUBEN JUAN';$array[209]['email'] = 'ORDENESCUEVASR@GMAIL.COM';
        // $array[210]['nombre'] = 'PEÑALOZA CEPEDA GLORIA ';$array[210]['email'] = 'GLORY.PENALOZA2013@GMAIL.COM';
        $array[211]['nombre'] = 'PEÑALOZA CEPEDA PAMELA ';$array[211]['email'] = 'PAMELA.PENALOZA84@GMAIL.COM';
        $array[212]['nombre'] = 'PEREZ ROCHA CAROL ';$array[212]['email'] = 'CAROLPEREZROCHA@GMAIL.COM';
        $array[213]['nombre'] = 'PEREZ SAN FRANCISCO MAURICIO';$array[213]['email'] = 'mipsanfrancisco90@gmail.com';
        $array[214]['nombre'] = 'RAMOS CAYO RODRIGO ';$array[214]['email'] = 'administracion@samutarapaca.cl';
        $array[215]['nombre'] = 'SEPULVEDA PADILLA SANDRA';$array[215]['email'] = 'SANDRA.SEP@HOTMAIL.COM';
        $array[216]['nombre'] = 'SOTO ALIAGA ERNESTO ';$array[216]['email'] = 'ER.SOTO.ALIAGA@GMAIL.COM';
        $array[217]['nombre'] = 'SOTO DIAZ JACQUELINE ';$array[217]['email'] = 'JSOTODIAZ351@GMAIL.COM';
        $array[218]['nombre'] = 'TAMBLAY VARELA CECILIA';$array[218]['email'] = 'CECILIA.TAMBLAY@REDSALUD.GOV.CL';
        $array[219]['nombre'] = 'VASQUEZ VERGARA LEYLA ';$array[219]['email'] = 'LEYLA.VASQUEZV@GMAIL.COM';
        $array[220]['nombre'] = 'VERNAL VASQUEZ CLAUDIA ';$array[220]['email'] = 'CPVV1972@GMAIL.COM';
        $array[221]['nombre'] = 'ACUÑA CASTILLO EDUARDO ';$array[221]['email'] = 'EDO.XTREMO@GMAIL.COM';
        $array[222]['nombre'] = 'ALMARZA GONZALEZ JOSE ';$array[222]['email'] = 'ALMARZAJ90@GMAIL.COM';
        $array[223]['nombre'] = 'ALVAREZ MEZA EDUARDO ';$array[223]['email'] = 'BERENGUELA7@GMAIL.COM';
        $array[224]['nombre'] = 'BARROS TORO SOFIA ';$array[224]['email'] = 'shofigoliat@gmail.com';
        $array[225]['nombre'] = 'CORTES CONTRERAS EMERSON ';$array[225]['email'] = 'EMERSONCORTESCONTRERAS@GMAIL.COM';
        $array[226]['nombre'] = 'FLORES FLORES JUANA ';$array[226]['email'] = 'JUANA.FLORES3561@GMAIL.COM';
        $array[227]['nombre'] = 'FLORES NUÑEZ SOLANGE ';$array[227]['email'] = 'SOLANGE.NUNEZ79@OUTLOOK.COM';
        $array[228]['nombre'] = 'GAJARDO ELIZONDO JOSE ';$array[228]['email'] = 'ESOJGAJARDO@GMAIL.COM';
        $array[229]['nombre'] = 'GORIGOITIA HERRERA CAROL ';$array[229]['email'] = 'CAROLGORIGOITIA2@GMAIL.COM';
        $array[230]['nombre'] = 'GUERRA RAMIREZ MATIAS ';$array[230]['email'] = 'MATIGUERRA007@GMAIL.COM';
        $array[231]['nombre'] = 'HUISCAÑANCO CASTEL RUBEN ';$array[231]['email'] = 'RUBEN.HUISCA.1980@GMAIL.COM';
        $array[232]['nombre'] = 'LAGUNAS ARRIAZA GONZALO';$array[232]['email'] = 'GONZALOLAGUNAS76@GMAIL.COM';
        $array[233]['nombre'] = 'LASTRA ALBORNOZ MANUEL ';$array[233]['email'] = 'MANUELLASTRA.A@GMAIL.COM';
        $array[234]['nombre'] = 'LINARES CARTAGENA JOSEFINA ';$array[234]['email'] = 'JOSEFINA.1997@GMAIL.COM';
        $array[235]['nombre'] = 'MUNDACA DIAZ DANIEL ';$array[235]['email'] = 'daniel.mundacad@gmail.com';
        $array[236]['nombre'] = 'NUÑEZ THIELE SUSAN ';$array[236]['email'] = 'THIARE_88@HOTMAIL.COM';
        $array[237]['nombre'] = 'OYARCE FLORES CARMEN ';$array[237]['email'] = 'CAREL.OYARCE@GMAIL.COM';
        $array[238]['nombre'] = 'PAEZ PAEZ WUANNER ';$array[238]['email'] = 'CAPA.ESTEBAN@GMAIL.COM';
        $array[239]['nombre'] = 'PEREZ SILVA MYRIAM';$array[239]['email'] = 'MYRIAMPEREZSILVA@GMAIL.COM';
        $array[240]['nombre'] = 'PORTILLA HERNANDEZ BERTA';$array[240]['email'] = 'VESOLE21@GMAIL.COM';
        $array[241]['nombre'] = 'RAMIREZ COLQUE DANIELA ';$array[241]['email'] = 'D.RAMIREZ.COLQUE@GMAIL.COM';
        $array[242]['nombre'] = 'RIQUELME BADILLA LAURA ';$array[242]['email'] = 'LAURITARUTRIQUELME@gmail.com';
        $array[243]['nombre'] = 'ROBLES BASUALTO SILVANA';$array[243]['email'] = 'SILVANA.ROBLES.2966@GMAIL.COM';
        $array[244]['nombre'] = 'ROJAS ZUÑIGA RICARDO';$array[244]['email'] = 'RICARDOROJASZ@HOTMAIL.COM';
        $array[245]['nombre'] = 'SAAVEDRA CARDENAS RODRIGO';$array[245]['email'] = 'fernandosaavedra2c@gmail.com';
        $array[246]['nombre'] = 'SANCHEZ CONTRERAS DANIEL';$array[246]['email'] = 'DANIEL5TA@HOTMAIL.COM';
        $array[247]['nombre'] = 'TAPIA ROSELLO ANA ';$array[247]['email'] = 'analuisatens@gimeil.com';
        $array[248]['nombre'] = 'UGALDE GANGAS JULIA ';$array[248]['email'] = 'diosaju@gmail.com';
        $array[249]['nombre'] = 'VERGARA ALLENDES PAULO ';$array[249]['email'] = 'PLOCO23@GMAIL.COM';
        $array[250]['nombre'] = 'VIDELA BISQUETT FRANCO ';$array[250]['email'] = 'F.VIDELA.BISQUETT@GMAIL.COM';
        $array[251]['nombre'] = 'VILCA CAYO TERESA ';$array[251]['email'] = 'tere.93.16@gmail.com';
        $array[252]['nombre'] = 'VILLALOBOS ARANCIBIA WILLIAMS';$array[252]['email'] = 'WILLIAMSVILLALOBOS3@GMAIL.COM';
        $array[253]['nombre'] = 'WIMMER RIOS JOHAN ';$array[253]['email'] = 'jwimmer72@gmail.com';
        $array[254]['nombre'] = 'ANDRADE OSORIO MANUEL';$array[254]['email'] = 'M.ANDROS37@GMAIL.COM';
        $array[255]['nombre'] = 'ARAYA ARAYA ALVARO';$array[255]['email'] = 'a.araya.psiquiatra@gmail.com';
        $array[256]['nombre'] = 'ASTUDILLO SÁNCHEZ MARIA';$array[256]['email'] = 'mveronica.astudillo@redsalud.gob.cl';
        $array[257]['nombre'] = 'DAPONTE MONTAÑO STEFANO';$array[257]['email'] = 'stefano.daponte@redasalud.gob.cl';
        $array[258]['nombre'] = 'TITIRO CASONE ALAN DIEGO';$array[258]['email'] = 'alan.titiro@gmail.com';
        $array[259]['nombre'] = 'VELASQUEZ BELTRAN MARCELA';$array[259]['email'] = 'marcela.velasquez.b@redsalud.gob.cl';
        $array[260]['nombre'] = 'ABUD MILOVIC NEVENKA FERNANDA';$array[260]['email'] = 'NEVENKAABUDM@GMAIL.COM';
        $array[261]['nombre'] = 'ACUÑA PEREIRA LUIS ANTONIO';$array[261]['email'] = 'LUACUNAPEREIRA@GMAIL.COM';
        $array[262]['nombre'] = 'ACUÑA RETAMAL SAMUEL';$array[262]['email'] = 'SAM.ACUNAR@GMAIL.COM';
        $array[263]['nombre'] = 'AEDO MAGNA JAVIERA FERNANDA';$array[263]['email'] = 'AEDOMAGNAJAVIERA@GMAIL.COM';
        $array[264]['nombre'] = 'AGUILERA RODRÍGUEZ NICOLÁS ';$array[264]['email'] = 'NAAR1995@GMAIL.COM';
        $array[265]['nombre'] = 'ALARCÓN RÍOS JOAQUÍN ANDRÉS';$array[265]['email'] = ' joaq.alarcon@gmail.com';
        $array[266]['nombre'] = 'ALARCON SARRIA TAHIA';$array[266]['email'] = 'TTALARCON1089@GMAIL.COM';
        $array[267]['nombre'] = 'ALVAREZ REA MILLARAY';$array[267]['email'] = 'milla.ar90@gmail.com';
        $array[268]['nombre'] = 'ANTOINE ORTIZ ELENA MARÍA';$array[268]['email'] = 'ELEANTOINE@GMAIL.COM';
        $array[269]['nombre'] = 'ARAYA CORTES ANTONIO';$array[269]['email'] = 'ANTINIOARAYACORTES@GMAIL.COM';
        $array[270]['nombre'] = 'ARAYA MARCHANT MANUEL IGNACIO';$array[270]['email'] = 'MANUELARAYA.MARCHANT@GMAIL.COM';
        $array[271]['nombre'] = 'AREVALO VALENZUELA MATIÁS ';$array[271]['email'] = 'MATIAS.AREVALO@MAIL.UDP.CL';
        $array[272]['nombre'] = 'AYARZA OLIVARES PAULA ANDREA';$array[272]['email'] = 'PA.AYARZA@GMAIL.COM';
        $array[273]['nombre'] = 'BARRÍA REYES LUIS EDUARDO';$array[273]['email'] = 'LEBARRIAREYES@HOTMAIL.COM';
        $array[274]['nombre'] = 'BERMÚDEZ GÓMEZ RODRIGO ANDRÉS';$array[274]['email'] = 'BERMUDEZ.GOMEZ@GMAIL.COM';
        $array[275]['nombre'] = 'BERRIOS BAEZA MAIRON DEREK';$array[275]['email'] = 'MAIRON.BERRIOS@GMAIL.COM';
        $array[276]['nombre'] = 'BRAVO MARAMBIO JAIME';$array[276]['email'] = 'JAIME.BRAVO.MED@GMAIL.COM';
        $array[277]['nombre'] = 'CABALLERO FONTECILLA CLAUDIA ';$array[277]['email'] = 'cbcaballerof@gmail.com';
        $array[278]['nombre'] = 'CAMPOS RAMIREZ OSCAR';$array[278]['email'] = 'alejandrapcamposr@gmail.com';
        $array[279]['nombre'] = 'CANCINO TORRES MARIO';$array[279]['email'] = 'MARIO.CANCINOT@GMAIL.COM';
        $array[280]['nombre'] = 'CARAFI LASO MARIA';$array[280]['email'] = 'rosariocarafi@gmail.com';
        $array[281]['nombre'] = 'CARRASCO GARCÍA PAULA FERNANDA';$array[281]['email'] = 'PAULA.CARRASCO.G@USACH.CL';
        $array[282]['nombre'] = 'CARTAGENA ARAVENA CARLOS';$array[282]['email'] = 'CARLOS.CARTAGENA.ARAVENA@GMAIL.COM';
        $array[283]['nombre'] = 'CASTILLO DAZA JAVIERA';$array[283]['email'] = 'JAVI.ROCIO14@GMAIL.COM';
        $array[284]['nombre'] = 'CASTRO IGLESIAS VICTOR ANDRÉS';$array[284]['email'] = 'CASTROIGLESIAS.V@GMAIL.COM';
        $array[285]['nombre'] = 'CASTRO MARTINEZ ALFREDO IGNACIO';$array[285]['email'] = 'alfredo.castro.m@ug.uchile.cl';
        $array[286]['nombre'] = 'CHAI GODOY AYLIN ALEJANDRA';$array[286]['email'] = 'aylin.chaigodoy@gmail.com';
        $array[287]['nombre'] = 'CONTRERAS ALIAGA VALERIA EDITH';$array[287]['email'] = 'VALECONTRERASA@UDEC.CL';
        $array[288]['nombre'] = 'CONTRERAS EBNER JAVIER';$array[288]['email'] = 'javiercontreras@udec.cl';
        $array[289]['nombre'] = 'CONTRERAS RAMOS OSCAR ADOLFO';$array[289]['email'] = 'OCONTRERASRAMOS@GMAIL.COM';
        $array[290]['nombre'] = 'CORNEJO GENERAL MÓNICA';$array[290]['email'] = 'MONICA.CORNEJOG@GMAIL.COM';
        $array[291]['nombre'] = 'CORTES LIRA GUILLERMO FELIPE';$array[291]['email'] = 'gfcortes7@gmail.com';
        $array[292]['nombre'] = 'CRUZ PEÑARANDA CAMILA';$array[292]['email'] = 'CAMILA.CRUZ@PENARANDA.CL';
        $array[293]['nombre'] = 'CUEVAS BARRIOS NATALIA ';$array[293]['email'] = 'NCUEVASBARRIOS@GMAIL.COM';
        $array[294]['nombre'] = 'DAZA MOYA MARÍA JESÚS';$array[294]['email'] = 'MDAZAMOYA@GMAIL.COM';
        $array[295]['nombre'] = 'DEICHLER TAPIA ALEXANDRA';$array[295]['email'] = 'ALEXANDRA.DEICHLERT@GMAIL.COM';
        $array[296]['nombre'] = 'DIAZ AGUIRRE JAVIERA VERÓNICA';$array[296]['email'] = 'JAVIERA.DIAZAGUIRRE@GMAIL.COM';
        $array[297]['nombre'] = 'DIBONA ALVARADO GONZALO ';$array[297]['email'] = 'BARDIELL@GMAIL.COM';
        $array[298]['nombre'] = 'DUPOUY CORTES JUAN';$array[298]['email'] = 'JUAN.DUPOUYC@GMAIL.COM';
        $array[299]['nombre'] = 'DURAN ESCOBAR DIEGO';$array[299]['email'] = 'dieduresc@gmail.com';
        $array[300]['nombre'] = 'EEDE MARTINEZ MELISSA ';$array[300]['email'] = 'MELISSA.EEDE@GMAIL.COM';
        $array[301]['nombre'] = 'ERAZO ASTUDILLO ISMAEL ';$array[301]['email'] = 'ismael.erazo@redsalud.gob.cl';
        $array[302]['nombre'] = 'ESPINOSA SIERRALTA FELIPE ';$array[302]['email'] = 'FELIPEESPINOSS11@GMAIL.COM';
        $array[303]['nombre'] = 'ESPINOZA NÚÑEZ JOAQUÍN ARTURO';$array[303]['email'] = 'joakoespinoza.n@gmail.com';
        $array[304]['nombre'] = 'ESPINOZA SOTOMAYOR DENISSE';$array[304]['email'] = 'denisse.espinozasotomayor@gmail.com';
        $array[305]['nombre'] = 'ETCHEVERRY MARDONES MAITE';$array[305]['email'] = 'MAITETCHEVERRY@GMAIL.COM';
        $array[306]['nombre'] = 'FARIAS VALDES JOAQUIN ';$array[306]['email'] = 'JOAQUIN.FARIASV@GMAIL.COM';
        $array[307]['nombre'] = 'FERNANDEZ LEAL VALENTINA';$array[307]['email'] = 'VALE.FERNANDEZLEAL@GMAIL.COM';
        $array[308]['nombre'] = 'FERNANDEZ TORRES MITZIE';$array[308]['email'] = 'MITZ.FERN@GMAIL.COM';
        $array[309]['nombre'] = 'FUENTES HUERTA SEBASTIAN FELIPE';$array[309]['email'] = 'SEBASTIAN.FUENTESH@HOTMAIL.COM';
        $array[310]['nombre'] = 'FUENTES KAY MARCO';$array[310]['email'] = 'mfuenteskay@gmail.com';
        $array[311]['nombre'] = 'FUENTES RODRIGUEZ DANIELA';$array[311]['email'] = 'danielafuentessr@gmail.com';
        $array[312]['nombre'] = 'GALIMANY ACOSTA JOSE';$array[312]['email'] = 'JOSEGALIMANYACOSTA@GMAIL.COM';
        $array[313]['nombre'] = 'GARCIA TRABUCCO CAMILA PAZ';$array[313]['email'] = 'CAMI.PAZGARCIA@GMAIL.COM';
        $array[314]['nombre'] = 'GARCIA VERGARA VALENTINA';$array[314]['email'] = 'VALEGV@LIVE.COM';
        $array[315]['nombre'] = 'GIUSTINIANOVICH FEHRMANN FELIPE';$array[315]['email'] = 'FELIPE.GIUSTINIANOVICH@MAIL.UDP.CL';
        $array[316]['nombre'] = 'GODOY COFRE IVAN';$array[316]['email'] = 'igodoy.med@gmail.com';
        $array[317]['nombre'] = 'GONZÁLEZ CULI DIEGO ALEJANDRO';$array[317]['email'] = 'diego.gonzalez.c@redsalud.gob.cl';
        $array[318]['nombre'] = 'GONZÁLEZ RODRÍGUEZ LEONARDO ';$array[318]['email'] = 'LGONZALEZR.95@GMAIL.COM';
        $array[319]['nombre'] = 'GRIGOLO JÁUREGUI STEFANO ';$array[319]['email'] = 'stefano.jauregui@gmail.com';
        $array[320]['nombre'] = 'GUZMÁN FREDES SOFÍA BEATRIZ';$array[320]['email'] = 'SOFIA.GUZMAN93@GMAIL.COM';
        $array[321]['nombre'] = 'HENRÍQUEZ COLOMA JAVIERA PAZ';$array[321]['email'] = 'JAVIERA.HENRIQUEZ.COLOMA@GMAIL.COM';
        $array[322]['nombre'] = 'HENRIQUEZ GUERRERO PEDRO';$array[322]['email'] = 'PPHG12@GMAIL.COM';
        $array[323]['nombre'] = 'HENRIQUEZ MATTA JAVIERA ';$array[323]['email'] = 'JAVIHENRIQUEZM@GMAIL.COM';
        $array[324]['nombre'] = 'HERRERA TORRES SEBASTIÁN ANÍBAL';$array[324]['email'] = 'sebastian.herrera@cormudesi.cl';
        $array[325]['nombre'] = 'IÑIGO VALDERRAMA MIRANDA ';$array[325]['email'] = 'MIRANDA.IVALDE@GMAIL.COM';
        $array[326]['nombre'] = 'IRIONDO CADIMA YESENIA EDITH';$array[326]['email'] = 'YESENIA.IRIONDO.CADIMA@GMAIL.COM';
        $array[327]['nombre'] = 'JEREZ VELÁSQUEZ NICOLÁS IGNACIO';$array[327]['email'] = 'NICOLAS.JEREZ@MAYOR.CL';
        $array[328]['nombre'] = 'KLINGER GUERRA ROBERTO';$array[328]['email'] = 'rklinger17@gmail.com';
        $array[329]['nombre'] = 'LEIVA BOHLE FERNANDO ANTONIO';$array[329]['email'] = 'FERNANDO.LEIVA.BOHLE@GMAIL.COM';
        $array[330]['nombre'] = 'LIRA MUÑOZ DANIEL';$array[330]['email'] = 'daniel.lira@redsalud.gob.cl';
        $array[331]['nombre'] = 'LOBOS LAGOS NATALIA';$array[331]['email'] = 'NATALIA.LOBOS.L@UG.UCHILE.CL';
        $array[332]['nombre'] = 'LOPEZ GOMEZ JORGE';$array[332]['email'] = 'JORGE.LG88@GMAIL.COM';
        $array[333]['nombre'] = 'LORCA CORTES PABLO ANTONIO';$array[333]['email'] = 'PABLO.LORCA@USACH.CL';
        $array[334]['nombre'] = 'LOYOLA DAZA MARÍA ISIDORA';$array[334]['email'] = 'DRAISIDORALOYOLA@GMAIL.COM';
        $array[335]['nombre'] = 'LOYOLA MORENO XIMENA';$array[335]['email'] = 'XIMENA.LOYOLA.M@GMAIL.COM';
        $array[336]['nombre'] = 'LOYOLA SALAS MARGOT ELISA';$array[336]['email'] = 'MARGOT.LOYOLA@USACH.CL';
        $array[337]['nombre'] = 'MARDONES CASTILLO JULIO ';$array[337]['email'] = 'JIMC90@GMAIL.COM';
        $array[338]['nombre'] = 'MASSIEL PÉREZ MACARENA BELÉN';$array[338]['email'] = 'macarena.massiel@ug.uchile.cl';
        $array[339]['nombre'] = 'MATURANA VALENZUELA CATALINA';$array[339]['email'] = 'cmaturanaval@gmail.com';
        $array[340]['nombre'] = 'MELLADO VILLEGAS EMANUEL ';$array[340]['email'] = 'E.MELLADO.VILLEGAS@GMAIL.COM';
        $array[341]['nombre'] = 'MIRANDA RODRIGUEZ LISSETTE ';$array[341]['email'] = 'LISSETTEMIRANDARODRIGUEZ@GMAIL.COM';
        $array[342]['nombre'] = 'MISLE ROJAS NICOLE';$array[342]['email'] = 'nicolemisle@gmail.com';
        $array[343]['nombre'] = 'MONTAÑA GALLEGUILLOS CAMILO';$array[343]['email'] = 'CAMONTGA@GMAIL.COM';
        $array[344]['nombre'] = 'MORA ARAYA JAVIERA CONSTANZA';$array[344]['email'] = 'JAVIERACONSTANZA.MA@GMAIL.COM';
        $array[345]['nombre'] = 'MUÑOZ GAJARDO FABIOLA ';$array[345]['email'] = 'cirugia200@gmail.com';
        $array[346]['nombre'] = 'MUÑOZ RUIZ KARLA ANGELICA';$array[346]['email'] = 'krlamunoz@hotmail.com';
        $array[347]['nombre'] = 'MUÑOZ SAEZ CARLOS';$array[347]['email'] = 'DR.MUNOZ.SAEZ@GMAIL.COM';
        $array[348]['nombre'] = 'MUÑOZ URQUEJO MARIA';$array[348]['email'] = 'MF.MURQUEJO@GMAIL.COM';
        $array[349]['nombre'] = 'NASER ACUÑA RENE';$array[349]['email'] = 'rene.naser.a@gmail.com';
        $array[350]['nombre'] = 'NAVARRETE GUZMAN SEBASTIAN';$array[350]['email'] = 'sebastian.navarrete.guzman@gmail.com';
        $array[351]['nombre'] = 'OLATE SAAVEDRA VANESSA';$array[351]['email'] = 'VAOLATESAA@GMAIL.COM';
        $array[352]['nombre'] = 'ORELLANA SANHUEZA ANDREA';$array[352]['email'] = 'Andrea.orellana.s@ug.uchile.cl';
        $array[353]['nombre'] = 'PALACIOS GALDAMES JAVIER ';$array[353]['email'] = 'JAVIEERPALACE@GMAIL.COM';
        $array[354]['nombre'] = 'PARDO OJEDA ANTONIA ANDREA';$array[354]['email'] = 'antonia.pardo@cormudespa.cl';
        $array[355]['nombre'] = 'PARRA FLORES AMBAR RUBÍ';$array[355]['email'] = 'ambar.flores12@gmail.com';
        $array[356]['nombre'] = 'PEREZ GUZMAN ANDREA ';$array[356]['email'] = 'ANDREAPEREZGUZMAN@GMAIL.COM';
        $array[357]['nombre'] = 'PEZOA SAN MARTÍN VALERIA';$array[357]['email'] = 'valeria.pezoa.s@gmail.com';
        $array[358]['nombre'] = 'PIZARRO ARANDA MAYRA';$array[358]['email'] = 'MDPIZARR@UC.CL';
        $array[359]['nombre'] = 'QUIJADA TAMARIN JENIFFER ';$array[359]['email'] = 'jeniffer.quijada.t@icloud.com';
        $array[360]['nombre'] = 'RAMÍREZ PÉREZ PAMELA';$array[360]['email'] = 'pamela.ramirezp@mayor.cl';
        $array[361]['nombre'] = 'RIQUELME RUIZ FRANCISCA';$array[361]['email'] = 'FRIQUELME@MEDICINA.UCSC.CL';
        $array[362]['nombre'] = 'RIVAS LAFERTE PIERA IGNACIA';$array[362]['email'] = 'Pierariv@gmail.com';
        $array[363]['nombre'] = 'RIVERA MANSILLA PAULINA SOFÍA';$array[363]['email'] = 'paulinasofia.rivera@gmail.com';
        $array[364]['nombre'] = 'ROCHA ARAYA CONSTANZA ANDREA';$array[364]['email'] = 'DRACONSTAZAROCHA@GMAIL.COM';
        $array[365]['nombre'] = 'RODRIGUEZ ALVAREZ CATALINA';$array[365]['email'] = 'catalina.rodriguez@ug.uchile.cl';
        $array[366]['nombre'] = 'ROJAS CANIUQUEO CLAUDIA ISABEL';$array[366]['email'] = 'claudia.rojas.c@redsalud.gob.cl';
        $array[367]['nombre'] = 'ROJAS ESCOBAR EMERSON ';$array[367]['email'] = 'EMERSON.ROJASESC@GMAIL.COM';
        $array[368]['nombre'] = 'ROJAS REYES DANIELA';$array[368]['email'] = 'DANIELA.ROJAS903@GMAIL.COM';
        $array[369]['nombre'] = 'ROMERO ARAYA PABLO FELIPE';$array[369]['email'] = 'PABLOROMEROARAYA@GMAIL.COM';
        $array[370]['nombre'] = 'ROSAS VARGAS SEBASTIÁN IGNACIO';$array[370]['email'] = 'SEBASTIAN.RV098@GMAIL.COM';
        $array[371]['nombre'] = 'SADE RODRIGUEZ AMIN';$array[371]['email'] = 'amin.sade@redsalud.gob.cl';
        $array[372]['nombre'] = 'SAENZ RAVELLO GUSTAVO ANTONIO';$array[372]['email'] = 'gustasaenzravello@gmail.com';
        $array[373]['nombre'] = 'SALAS CORNEJO PAULINA';$array[373]['email'] = 'PVSALASC@GMAIL.COM';
        $array[374]['nombre'] = 'SALDIAS MOATTE MIGUEL';$array[374]['email'] = 'saldiasmiguel8@gmail.com';
        $array[375]['nombre'] = 'SALGADO TAPIA FELIPE EDUARDO';$array[375]['email'] = 'fsalgadotapia@gmail.com';
        $array[376]['nombre'] = 'SALINAS ANGEL VICENTE ';$array[376]['email'] = 'VASALINASA@GMAIL.COM';
        $array[377]['nombre'] = 'SALINAS VILLAGRA MARCELO';$array[377]['email'] = 'msalinasv@uft.edu';
        $array[378]['nombre'] = 'SCHWERTER LILLO JAVIER IGNACIO';$array[378]['email'] = 'JISHWETER@UC.CL';
        $array[379]['nombre'] = 'SEGURA PALLACAN CECILIA';$array[379]['email'] = 'CECIANDREA.SE@GMAIL.COM';
        $array[380]['nombre'] = 'SEPÚLVEDA ROSALES VALENTINA';$array[380]['email'] = 'VALE.SEPULVEDAR@HOTMAIL.COM';
        $array[381]['nombre'] = 'SUAREZ LEIVA IVANIA';$array[381]['email'] = 'ISULE.10@GMAIL.COM';
        $array[382]['nombre'] = 'TOLEDO LAY SEBASTIAN';$array[382]['email'] = 'STOLEDOLAY@GMAIL.COM';
        $array[383]['nombre'] = 'TORREJÓN WEBER ROSARIO ANTONIA';$array[383]['email'] = 'ROSARIOATW@GMAIL.COM';
        $array[384]['nombre'] = 'TORRES VENEGAS RENÉ';$array[384]['email'] = 'TORRES.VENEGAS@GMAIL.COM';
        $array[385]['nombre'] = 'VALDERRAMA VILLEGAS ALBERTO ';$array[385]['email'] = 'ALBERTO.VALDERRAMA.V@GMAIL.COM';
        $array[386]['nombre'] = 'VALENZUELA ARANDA KIMBERLY ';$array[386]['email'] = 'KIMBERLY.VALENZUELA2011@GMAIL.COM';
        $array[387]['nombre'] = 'VALLE SALAZAR GABRIELA SOFIA';$array[387]['email'] = 'GSVALLE@UC.CL';
        $array[388]['nombre'] = 'VARAS MUÑOZ JAVIERA PAZ';$array[388]['email'] = 'VARASJAVIERA8@GMAIL.COM';
        $array[389]['nombre'] = 'VERA SANTIS GONZALO';$array[389]['email'] = 'gon.vera1992@gmail.com';
        $array[390]['nombre'] = 'VERGARA JACKSON ANDRÉS ALAN';$array[390]['email'] = 'VERGARAJACKSONA@GMAIL.COM';
        $array[391]['nombre'] = 'VERGARA SALVAT CATALINA ADRIANA';$array[391]['email'] = 'CATALINA.VERGARAS@MAYOR.CL';
        $array[392]['nombre'] = 'VILLALOBOS BERNAL MARIELA';$array[392]['email'] = 'NINATOPIA@HOTMAIL.COM';
        $array[393]['nombre'] = 'VILLANUEVA BONILLA SEBASTIAN';$array[393]['email'] = 'VILLANUEVABONILLA1@GMAIL.COM';
        $array[394]['nombre'] = 'ZENTENO BARRA GUSTAVO ADOLFO';$array[394]['email'] = 'GUSTAVO.ZENTENOB@GMAIL.COM';
        $array[395]['nombre'] = 'ZENTENO BARRA SERGIO';$array[395]['email'] = 'SERGIO.ZENTENOBARRA05@GMAIL.COM';
        $array[396]['nombre'] = 'BENAVIDES GONZALEZ SERGIO ';$array[396]['email'] = 'medico.regulador@samutarapaca.cl';
        $array[397]['nombre'] = 'CAIPA ESTAY JULIAN ';$array[397]['email'] = 'julian.caipa@redsalud.gob.cl';
        $array[398]['nombre'] = 'CALVO VARAS CARLOS ';$array[398]['email'] = 'carlos.calvo@redsalud.gov.cl';
        $array[399]['nombre'] = 'CALVO VARAS JAVIER ';$array[399]['email'] = 'javier.calvov@redsalud.gob.cl';
        $array[400]['nombre'] = 'CAMPOS HILAJA GRACIELY ';$array[400]['email'] = 'graciely.campos@redsalud.gob.cl';
        $array[401]['nombre'] = 'CARRILLO LIOI DIEGO ';$array[401]['email'] = 'diego.carrillo@redsalud.gob.cl';
        $array[402]['nombre'] = 'CASTRO OPORTO JORGE ';$array[402]['email'] = 'jorge.castroo@redsalud.gob.cl';
        $array[403]['nombre'] = 'CELEDON CHING JAVIERA';$array[403]['email'] = 'javiera.celedon@redsalud.gob.cl';
        $array[404]['nombre'] = 'DIAZ LAZO RAUL ';$array[404]['email'] = 'DIAZ_LAZO_RAUL@HOTMAIL.COM';
        $array[405]['nombre'] = 'ESQUIVEL MESIAS MARCELA ';$array[405]['email'] = 'mesquivelm82@gmail.com';
        $array[406]['nombre'] = 'FARIÑA KUTZ LORENA ';$array[406]['email'] = 'EFARINAKUTZ@GMAIL.COM';
        $array[407]['nombre'] = 'FLORES ARAYA FREDY ';$array[407]['email'] = 'FAFREDY@HOTMAIL.COM';
        $array[408]['nombre'] = 'FONT CARMONA JORGE';$array[408]['email'] = 'jorge.font@redsalud.gob.cl';
        $array[409]['nombre'] = 'GOMEZCOELLO SALINAS FANNY ';$array[409]['email'] = 'fanny.gomezcoello@redsalud.gov.cl';
        $array[410]['nombre'] = 'HERRERA GAMBOA PIA ';$array[410]['email'] = 'PIAHERRERAGAMBOA@GMAIL.COM';
        $array[411]['nombre'] = 'LEIVA MIRANDA SILVIA';$array[411]['email'] = 'silvia.leivamiranda@gmail.com';
        $array[412]['nombre'] = 'LEYTON LABBE DIEGO ';$array[412]['email'] = 'diego.leyton@redsalud.gob.cl';
        $array[413]['nombre'] = 'MALUENDA ESPINA JOSE ';$array[413]['email'] = 'jose.maluenda@redsalud.gob.cl';
        $array[414]['nombre'] = 'MATAYOSHI MACHIDA KAORU';$array[414]['email'] = 'kaoru.matayoshi@redsalud.gob.cl';
        $array[415]['nombre'] = 'MENDEZ QUILODRAN NAYARET ';$array[415]['email'] = 'nayaret.mendez@redsalud.gob.cl';
        $array[416]['nombre'] = 'MERIÑO SOTO JEAN PAUL ';$array[416]['email'] = 'jpaul.merino@redsalud.gob.cl';
        $array[417]['nombre'] = 'MOLINA ALVAREZ FERNANDO ';$array[417]['email'] = 'fernando.molina@redsalud.gov.cl';
        $array[418]['nombre'] = 'ORTEGA GOMEZ HUGO ';$array[418]['email'] = 'hugo.ortega.g@redsalud.gob.cl';
        $array[419]['nombre'] = 'ORTEGA GOMEZ HUGO ';$array[419]['email'] = 'hugo.ortega.g@redsalud.gob.cl';
        $array[420]['nombre'] = 'PARDO MORENO MAURICIO';$array[420]['email'] = 'maopm@yahoo.com';
        $array[421]['nombre'] = 'PAVEZ ZAPATA CHRISTIAN ';$array[421]['email'] = 'christian.pavez@redsalud.gob.cl';
        $array[422]['nombre'] = 'ROJAS CAPETILLO JOSELYN ';$array[422]['email'] = 'jose.rojass02@gmail.com';
        $array[423]['nombre'] = 'ROJAS LIZONDO ENRIQUE ';$array[423]['email'] = 'enrique.rojasl@redsalud.gob.cl';
        $array[424]['nombre'] = 'SANTOS RAMOS ELIZABETH ';$array[424]['email'] = 'elizabethsantos7@gmail.com';
        $array[425]['nombre'] = 'TELLO ESPINOZA VANESSA ';$array[425]['email'] = 'vanessa.tello@redsalud.gob.cl';
        $array[426]['nombre'] = 'VILLAGRA SALFATI JANELL';$array[426]['email'] = 'janell.villagra@redsalud.gob.cl';



        foreach($array as $key => $user){
            
            Notification::route('mail', [$user['email'] => $user['nombre'],])->notify(new SystemNotification($user));
            print($key . ": " . $user['nombre'] . "  OK \n");
        }

        

        return Command::SUCCESS;
    }
}
