<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AbsenteeismTypesSeeder extends Seeder
{
    public function run()
    {
        DB::table('rrhh_absenteeism_types')->insert([
            [
                'name' => 'L.M. ENFERMEDAD',
                'discount' => 1,
                'half_day' => 0,
                'count_business_days' => 0,
                'from' => null,
                'over' => null,
                'created_at' => Carbon::parse('2023-08-23 13:27:07'),
                'updated_at' => Carbon::parse('2023-10-05 17:07:43'),
            ],
            [
                'name' => 'COMISION DE SERVICIO',
                'discount' => 1,
                'half_day' => 1,
                'count_business_days' => 0,
                'from' => 0.50,
                'over' => 1.00,
                'created_at' => Carbon::parse('2024-10-07 06:32:43'),
                'updated_at' => null,
            ],
            [
                'name' => 'FERIADOS LEGALES',
                'discount' => 1,
                'half_day' => null,
                'count_business_days' => null,
                'from' => null,
                'over' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'name' => 'PERMISOS ADMINISTRATIVOS',
                'discount' => 1,
                'half_day' => 0,
                'count_business_days' => 0,
                'from' => 1.00,
                'over' => null,
                'created_at' => Carbon::parse('2023-12-06 08:04:04'),
                'updated_at' => Carbon::parse('2023-12-06 08:04:04'),
            ],
            [
                'name' => 'DIAS COMPENSATORIOS',
                'discount' => 1,
                'half_day' => 0,
                'count_business_days' => 0,
                'from' => null,
                'over' => 1.00,
                'created_at' => Carbon::parse('2023-12-06 08:04:08'),
                'updated_at' => Carbon::parse('2023-12-06 08:04:08'),
            ],
            [
                'name' => 'SUSP. EMP. MED. DISCIPLINARIA',
                'discount' => 1,
                'half_day' => null,
                'count_business_days' => null,
                'from' => null,
                'over' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'name' => 'TELETRABAJO FUNCIONES NO HABITUALES',
                'discount' => 0,
                'half_day' => 0,
                'count_business_days' => 0,
                'from' => null,
                'over' => null,
                'created_at' => Carbon::parse('2023-10-05 17:07:35'),
                'updated_at' => null,
            ],
            [
                'name' => 'PERMISO DESCANSO REPARATORIO',
                'discount' => 1,
                'half_day' => null,
                'count_business_days' => null,
                'from' => null,
                'over' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'name' => 'TELETRABAJO FUNCIONES HABITUALES',
                'discount' => 0,
                'half_day' => 0,
                'count_business_days' => 0,
                'from' => null,
                'over' => null,
                'created_at' => Carbon::parse('2023-10-05 17:07:32'),
                'updated_at' => null,
            ],
            [
                'name' => 'L.M. ACCIDENTE EN LUGAR DE TRABAJO',
                'discount' => 1,
                'half_day' => null,
                'count_business_days' => null,
                'from' => null,
                'over' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'name' => 'L.M. ACCIDENTE EN TRAYECTORIA AL TRABAJO',
                'discount' => 1,
                'half_day' => null,
                'count_business_days' => null,
                'from' => null,
                'over' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'name' => 'PERMISOS S/SUELDOS',
                'discount' => 1,
                'half_day' => null,
                'count_business_days' => null,
                'from' => null,
                'over' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'name' => 'L.M. ENFERMEDAD PROFESIONAL',
                'discount' => 1,
                'half_day' => null,
                'count_business_days' => null,
                'from' => null,
                'over' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'name' => 'L.M. MATERNAL',
                'discount' => 1,
                'half_day' => null,
                'count_business_days' => null,
                'from' => null,
                'over' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'name' => 'L.M. PATOLOGIA DEL EMBARAZO',
                'discount' => 1,
                'half_day' => null,
                'count_business_days' => null,
                'from' => null,
                'over' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'name' => 'POSTNATAL PARENTAL',
                'discount' => 1,
                'half_day' => null,
                'count_business_days' => null,
                'from' => null,
                'over' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'name' => 'L.M. PRORROGA DE MEDICINA PREVENTIVA',
                'discount' => 1,
                'half_day' => null,
                'count_business_days' => null,
                'from' => null,
                'over' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'name' => 'PERMISO GREMIAL',
                'discount' => 0,
                'half_day' => 0,
                'count_business_days' => 0,
                'from' => null,
                'over' => null,
                'created_at' => Carbon::parse('2023-10-05 17:07:19'),
                'updated_at' => null,
            ],
            [
                'name' => 'L.M. ENFERMEDAD GRAVE HIJO MENOR DE UN AÑO',
                'discount' => 1,
                'half_day' => 0,
                'count_business_days' => 0,
                'from' => null,
                'over' => null,
                'created_at' => Carbon::parse('2023-10-05 17:07:13'),
                'updated_at' => null,
            ],
            [
                'name' => 'FALLECIMIENTO HERMANO/A',
                'discount' => 1,
                'half_day' => 0,
                'count_business_days' => 0,
                'from' => null,
                'over' => null,
                'created_at' => Carbon::parse('2023-10-05 17:07:09'),
                'updated_at' => null,
            ],
            [
                'name' => 'PERMISO SANNA',
                'discount' => 1,
                'half_day' => null,
                'count_business_days' => null,
                'from' => null,
                'over' => null,
                'created_at' => Carbon::parse('2023-12-29 08:37:28'),
                'updated_at' => Carbon::parse('2023-12-29 08:37:28'),
            ],
            [
                'name' => 'FALLECIMIENTO PADRE',
                'discount' => 1,
                'half_day' => null,
                'count_business_days' => null,
                'from' => null,
                'over' => null,
                'created_at' => Carbon::parse('2023-12-29 08:37:12'),
                'updated_at' => Carbon::parse('2023-12-29 08:37:12'),
            ],
        ]);
    }
}
