<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Resources\Telephone;
use App\Models\User;

class TelephoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $telephone = Telephone::Create(['number' => 572406984, 'minsal' => 576984]);
        $telephone->users()->attach(User::find(15287582));

        $telephone = Telephone::Create(['number' => 572539004, 'minsal' => 579004]);
        $telephone->users()->attach(User::find(10278387));

        $telephone = Telephone::Create(['number' => 572539008, 'minsal' => 579008]);
        $telephone->users()->attach(User::find(14107361));

        $telephone = Telephone::Create(['number' => 572539009, 'minsal' => 579009]);
        $telephone->users()->attach(User::find(15924400));

        $telephone = Telephone::Create(['number' => 572539518, 'minsal' => 579518]);
        $telephone->users()->attach(User::find(16966444));

        /**
         * Create 10 random telephones.
         */
        //factory(App\Models\Resources\Telephone::class, 10)->create();


        $telephones = [
            ['minsal' => '575700', 'number' => '575700', 'visualization' => 'OPERADORA', 'service' => 'OPERADORA'],
            ['minsal' => '575701', 'number' => '575701', 'visualization' => 'OIRS 1', 'service' => 'OIRS'],
            ['minsal' => '575702', 'number' => '575702', 'visualization' => 'OIRS 2', 'service' => 'OIRS'],
            ['minsal' => '575703', 'number' => '575703', 'visualization' => 'INFORMACIONES URGENCIA', 'service' => 'INFORMACIONES'],
            ['minsal' => '575706', 'number' => '575706', 'visualization' => 'JEFE ANATOMIA PATOLOGICA', 'service' => 'ANATOMIA PATOLOGICA'],
            ['minsal' => '575707', 'number' => '575707', 'visualization' => 'SECRETARIA 1 ANAT. PATOL.', 'service' => 'ANATOMIA PATOLOGICA'],
            ['minsal' => '575708', 'number' => '575708', 'visualization' => 'SECRETARIA 2 ANAT. PATOL.', 'service' => 'ANATOMIA PATOLOGICA'],
            ['minsal' => '575709', 'number' => '575709', 'visualization' => 'TECNOLOGO ANAT. PATOL.', 'service' => 'ANATOMIA PATOLOGICA'],
            ['minsal' => '575710', 'number' => '575710', 'visualization' => 'PATOLOGO ANAT. PATOL.', 'service' => 'ANATOMIA PATOLOGICA'],
            ['minsal' => '575711', 'number' => '575711', 'visualization' => 'ESTAR ANAT. PATOL.', 'service' => 'ANATOMIA PATOLOGICA'],
            ['minsal' => '575712', 'number' => '575712', 'visualization' => 'LAB. CITOLOGIA ANAT. PATOL.', 'service' => 'ANATOMIA PATOLOGICA'],
            ['minsal' => '575713', 'number' => '575713', 'visualization' => 'LAB. HISTOLOGIA ANAT. PATOL.', 'service' => 'ANATOMIA PATOLOGICA'],
            ['minsal' => '575714', 'number' => '575714', 'visualization' => 'NECROPSIA ANAT. PATOL.', 'service' => 'ANATOMIA PATOLOGICA'],
            ['minsal' => '575715', 'number' => '575715', 'visualization' => 'JEFE PENSIONADO', 'service' => 'PENSIONADO'],
            ['minsal' => '575716', 'number' => '575716', 'visualization' => 'SECRETARIA PENSIONADO', 'service' => 'PENSIONADO'],
            ['minsal' => '575717', 'number' => '575717', 'visualization' => 'Jefe Remuneraciones', 'service' => 'RECAUDACION'],
            ['minsal' => '575718', 'number' => '575718', 'visualization' => 'ADMINISTRATIVO PENSIONADO', 'service' => 'PENSIONADO'],
            ['minsal' => '575719', 'number' => '575719', 'visualization' => 'EST. ENF. PENSIONADO', 'service' => 'PENSIONADO'],
            ['minsal' => '575720', 'number' => '575720', 'visualization' => 'VALORIZACION 1 PENSIONADO', 'service' => 'PENSIONADO'],
            ['minsal' => '575721', 'number' => '575721', 'visualization' => 'VALORIZACION 2 PENSIONADO', 'service' => 'PENSIONADO'],
            ['minsal' => '575722', 'number' => '575722', 'visualization' => 'ENCARGADO FINANZAS', 'service' => 'FINANZAS'],
            ['minsal' => '575723', 'number' => '575723', 'visualization' => 'HABITACION 1 A y B', 'service' => 'CAE B'],
            ['minsal' => '575724', 'number' => '575724', 'visualization' => 'C.FRIO B.VACUNAS', 'service' => 'VACUNAS'],
            ['minsal' => '575731', 'number' => '575731', 'visualization' => 'PRQX Secretaria', 'service' => 'PREQX'],
            ['minsal' => '575732', 'number' => '575732', 'visualization' => 'DOCENCIA', 'service' => 'DOCENCIA'],
            ['minsal' => '575735', 'number' => '575735', 'visualization' => 'secretaria neurocirugia', 'service' => 'NEUROCIRUGIA'],
            ['minsal' => '575737', 'number' => '575737', 'visualization' => 'HABITACION 15', 'service' => 'HABITACION'],
            ['minsal' => '575738', 'number' => '575738', 'visualization' => 'HABITACION 16', 'service' => 'HABITACION'],
            ['minsal' => '575739', 'number' => '575739', 'visualization' => 'HABITACION 17', 'service' => 'HABITACION'],
            ['minsal' => '575740', 'number' => '575740', 'visualization' => 'HABITACION 18', 'service' => 'HABIT MATRONA'],
            ['minsal' => '575741', 'number' => '575741', 'visualization' => 'REAS', 'service' => 'REAS'],
            ['minsal' => '575742', 'number' => '575742', 'visualization' => 'MEDICINA 1', 'service' => 'MEDICINA'],
            ['minsal' => '575745', 'number' => '575745', 'visualization' => 'ESTAR PROF. PENSIONADO', 'service' => 'PENSIONADO'],
            ['minsal' => '575746', 'number' => '575746', 'visualization' => 'CASINO PENSIONADO', 'service' => 'PENSIONADO'],
            ['minsal' => '575747', 'number' => '575747', 'visualization' => 'REPOSTERIA PENSIONADO', 'service' => 'PENSIONADO'],
            ['minsal' => '575748', 'number' => '575748', 'visualization' => 'JEFE LAVANDERIA', 'service' => 'LAVANDERIA'],
            ['minsal' => '575749', 'number' => '575749', 'visualization' => 'SECRETARIA LAVANDERIA', 'service' => 'LAVANDERIA'],
            ['minsal' => '575750', 'number' => '575750', 'visualization' => 'BODEGA LAVANDERIA', 'service' => 'LAVANDERIA'],
            ['minsal' => '575751', 'number' => '575751', 'visualization' => 'BOD. PQTE. CENT. LAV.', 'service' => 'LAVANDERIA'],
            ['minsal' => '575752', 'number' => '575752', 'visualization' => 'ROPERIA LAVANDERIA', 'service' => 'LAVANDERIA'],
            ['minsal' => '575753', 'number' => '575753', 'visualization' => 'AREA LIMPIA LAVANDERIA', 'service' => 'LAVANDERIA'],
            ['minsal' => '575754', 'number' => '575754', 'visualization' => 'SECADO LAVANDERIA', 'service' => 'LAVANDERIA'],
            ['minsal' => '575755', 'number' => '575755', 'visualization' => 'ESTAR LAVANDERIA', 'service' => 'LAVANDERIA'],
            ['minsal' => '575756', 'number' => '575756', 'visualization' => 'AREA SUCIA LAVANDERIA', 'service' => 'LAVANDERIA'],
            ['minsal' => '575758', 'number' => '575758', 'visualization' => 'JEFE BANCO SANGRE', 'service' => 'UMT'],
            ['minsal' => '575759', 'number' => '575759', 'visualization' => 'PASILLO PRINCIPAL BS', 'service' => 'UMT'],
            ['minsal' => '575760', 'number' => '575760', 'visualization' => 'RESIDENCIA BCO. SANGRE', 'service' => 'UMT'],
            ['minsal' => '575761', 'number' => '575761', 'visualization' => 'PASILLO RESIDENCIA BS', 'service' => 'UMT'],
            ['minsal' => '575762', 'number' => '575762', 'visualization' => 'INMUNOLOGIA BCO. SANGRE', 'service' => 'UMT'],
            ['minsal' => '575763', 'number' => '575763', 'visualization' => 'HEMODERIVADOS BCO. SANGRE', 'service' => 'UMT'],
            ['minsal' => '575764', 'number' => '575764', 'visualization' => 'LABORATORIO DE SANGRE', 'service' => 'UMT'],
            ['minsal' => '575765', 'number' => '575765', 'visualization' => 'SALA ENCUESTA BCO. SANGRE', 'service' => 'UMT'],
            ['minsal' => '575766', 'number' => '575766', 'visualization' => 'SECRETARIA BCO. SANGRE', 'service' => 'UMT'],
            ['minsal' => '575767', 'number' => '575767', 'visualization' => 'RECEPCION SALUD TRABAJADOR', 'service' => 'SALUD TRABAJADOR'],
            ['minsal' => '575768', 'number' => '575768', 'visualization' => 'MODULO ADMINISTRACION 1', 'service' => 'ADMINISTRACION'],
            ['minsal' => '575769', 'number' => '575769', 'visualization' => 'ADM. APOYO BIBLIOTECA', 'service' => 'BIBLIOTECA'],
            ['minsal' => '575770', 'number' => '575770', 'visualization' => 'ENCARGADA BIBLIOTECA', 'service' => 'BIBLIOTECA'],
            ['minsal' => '575772', 'number' => '575772', 'visualization' => 'INFORMACIONES', 'service' => 'INFORMACIONES'],
            ['minsal' => '575774', 'number' => '575774', 'visualization' => 'JEFE CAPACITACION', 'service' => 'CAPACITACION'],
            ['minsal' => '575775', 'number' => '575775', 'visualization' => 'PROF. 1 CAPACITACION', 'service' => 'CAPACITACION'],
            ['minsal' => '575776', 'number' => '575776', 'visualization' => 'SECRETARIA CAPACITACION', 'service' => 'CAPACITACION'],
            ['minsal' => '575777', 'number' => '575777', 'visualization' => 'PRQX ENFERMERA 2', 'service' => 'PREQX'],
            ['minsal' => '575778', 'number' => '575778', 'visualization' => 'Unidad de Docencia', 'service' => 'Docencia'],
            ['minsal' => '575779', 'number' => '575779', 'visualization' => 'PROF. 2 CAPACITACION', 'service' => 'CAPACITACION'],
            ['minsal' => '575780', 'number' => '575780', 'visualization' => 'PERIODISTA', 'service' => 'PERIODISTA'],
            ['minsal' => '575781', 'number' => '575781', 'visualization' => 'TRAUMATOLOGIA PREQX', 'service' => 'PREQX'],
            ['minsal' => '575782', 'number' => '575782', 'visualization' => 'JEFE CENTRAL ALIMENTACION', 'service' => 'ALIMENTACION'],
            ['minsal' => '575783', 'number' => '575783', 'visualization' => 'SECREATRIA C. ALIMENTACION', 'service' => 'ALIMENTACION'],
            ['minsal' => '575784', 'number' => '575784', 'visualization' => 'PASILLO COCINA C. ALIMENTA.', 'service' => 'ALIMENTACION'],
            ['minsal' => '575785', 'number' => '575785', 'visualization' => 'OF. 1 NUTRICIONISTA C. ALIM.', 'service' => 'ALIMENTACION'],
            ['minsal' => '575786', 'number' => '575786', 'visualization' => 'OF. 2 NUTRICIONISTA C. ALIM.', 'service' => 'ALIMENTACION'],
            ['minsal' => '575787', 'number' => '575787', 'visualization' => 'BODEGA C. ALIMENTACION', 'service' => 'ALIMENTACION'],
            ['minsal' => '575788', 'number' => '575788', 'visualization' => 'CASINO', 'service' => 'CASINO'],
            ['minsal' => '575789', 'number' => '575789', 'visualization' => 'SEDILE 1', 'service' => 'SEDILE'],
            ['minsal' => '575790', 'number' => '575790', 'visualization' => 'SEDILE 2', 'service' => 'SEDILE'],
            ['minsal' => '575791', 'number' => '575791', 'visualization' => 'SEDILE 3', 'service' => 'SEDILE'],
            ['minsal' => '575793', 'number' => '575793', 'visualization' => 'Secretaria SOME', 'service' => 'SOME'],
            ['minsal' => '575794', 'number' => '575794', 'visualization' => 'JEFE CENTRAL ESTERILIZACION', 'service' => 'ESTERILIZACION'],
            ['minsal' => '575795', 'number' => '575795', 'visualization' => 'SECRETARIA C. ESTERIL.', 'service' => 'ESTERILIZACION'],
            ['minsal' => '575797', 'number' => '575797', 'visualization' => 'MAT. ESTERIL C. ESTERIL.', 'service' => 'ESTERILIZACION'],
            ['minsal' => '575798', 'number' => '575798', 'visualization' => 'MESON DE CORTE C. EST.', 'service' => 'ESTERILIZACION'],
            ['minsal' => '575799', 'number' => '575799', 'visualization' => 'Medico Psiquiatria', 'service' => 'PSIQUIATRIA'],
            ['minsal' => '575800', 'number' => '575800', 'visualization' => 'SALA GUANTES C. ESTERIL.', 'service' => 'ESTERILIZACION'],
            ['minsal' => '575801', 'number' => '575801', 'visualization' => 'RECEP. MAT. SUCIO C. EST.', 'service' => 'ESTERILIZACION'],
            ['minsal' => '575802', 'number' => '575802', 'visualization' => 'PREP. MAT. CURACION C. EST.', 'service' => 'ESTERILIZACION'],
            ['minsal' => '575803', 'number' => '575803', 'visualization' => 'EST. ENF. CMA', 'service' => 'CMA'],
            ['minsal' => '575804', 'number' => '575804', 'visualization' => 'SUPERVISORA CMA CIRUGIA MAYOR', 'service' => 'CMA'],
            ['minsal' => '575806', 'number' => '575806', 'visualization' => 'EST. ENF. NEUROCIRUGIA', 'service' => 'NEUROCIRUGIA'],
            ['minsal' => '575807', 'number' => '575807', 'visualization' => 'JEFE CONS. ESPECIALIDADES', 'service' => 'CAE'],
            ['minsal' => '575808', 'number' => '575808', 'visualization' => 'SECRETARIA 1 C. ESPEC.', 'service' => 'CAE'],
            ['minsal' => '575809', 'number' => '575809', 'visualization' => 'SECRETARIA 2 C. ESPEC.', 'service' => 'CAE'],
            ['minsal' => '575810', 'number' => '575810', 'visualization' => 'SUPERVISOR C. ESPEC.', 'service' => 'CAE'],
            ['minsal' => '575811', 'number' => '575811', 'visualization' => 'SUPERVISOR GES C. ESPEC.', 'service' => 'CAE'],
            ['minsal' => '575812', 'number' => '575812', 'visualization' => 'ASISTENTE SOCIAL C. ESPEC.', 'service' => 'CAE'],
            ['minsal' => '575815', 'number' => '575815', 'visualization' => 'SECRE.HOSP.DOMICILIARIA', 'service' => 'HOSPITALIZACION DOMICILIARIA'],
            ['minsal' => '575816', 'number' => '575816', 'visualization' => 'JEFE DAIS', 'service' => 'DAIS'],
            ['minsal' => '575817', 'number' => '575817', 'visualization' => 'PLANIF. Y CONTROL', 'service' => 'PLANIFICACION'],
            ['minsal' => '575818', 'number' => '575818', 'visualization' => 'DIGITADOR 1 GES', 'service' => 'GES'],
            ['minsal' => '575819', 'number' => '575819', 'visualization' => 'DIGITADOR 3 GES', 'service' => 'GES'],
            ['minsal' => '575820', 'number' => '575820', 'visualization' => 'DIGITADOR 2 GES', 'service' => 'GES'],
            ['minsal' => '575821', 'number' => '575821', 'visualization' => 'COBRANZA E ISAPRE', 'service' => 'COBRANZA'],
            ['minsal' => '575822', 'number' => '575822', 'visualization' => 'GES 1', 'service' => 'GES'],
            ['minsal' => '575823', 'number' => '575823', 'visualization' => 'ESTADISTICO 3', 'service' => 'GES'],
            ['minsal' => '575824', 'number' => '575824', 'visualization' => 'ESTADISTICO 4', 'service' => 'GES'],
            ['minsal' => '575825', 'number' => '575825', 'visualization' => 'Monitor Registro SIGGES', 'service' => 'SIGGES'],
            ['minsal' => '575826', 'number' => '575826', 'visualization' => 'ESTADISTICO 6', 'service' => 'GES'],
            ['minsal' => '575827', 'number' => '575827', 'visualization' => 'Registro GES Oftalmologia', 'service' => 'GES'],
            ['minsal' => '575828', 'number' => '575828', 'visualization' => 'ASFUNSHI', 'service' => 'ASFUNSHI'],
            ['minsal' => '575829', 'number' => '575829', 'visualization' => 'calidad de vida 1', 'service' => 'CALIDAD DE VIDA'],
            ['minsal' => '575830', 'number' => '575830', 'visualization' => 'Dental Box 7', 'service' => 'DENTAL'],
            ['minsal' => '575831', 'number' => '575831', 'visualization' => 'BOX DENTAL 6', 'service' => 'DENTAL'],
            ['minsal' => '575832', 'number' => '575832', 'visualization' => 'BOX DENTAL 4', 'service' => 'DENTAL'],
            ['minsal' => '575833', 'number' => '575833', 'visualization' => 'BOX DENTAL 5', 'service' => 'DENTAL'],
            ['minsal' => '575834', 'number' => '575834', 'visualization' => 'SALA INFORME DENTAL', 'service' => 'DENTAL'],
            ['minsal' => '575835', 'number' => '575835', 'visualization' => 'BOX DENTAL 1', 'service' => 'DENTAL'],
            ['minsal' => '575836', 'number' => '575836', 'visualization' => 'BOX DENTAL 2', 'service' => 'DENTAL'],
            ['minsal' => '575837', 'number' => '575837', 'visualization' => 'BOX DENTAL 3', 'service' => 'DENTAL'],
            ['minsal' => '575838', 'number' => '575838', 'visualization' => 'ESTAR DENTAL', 'service' => 'DENTAL'],
            ['minsal' => '575839', 'number' => '575839', 'visualization' => 'SALA 1 DENTAL THOMPSON', 'service' => 'DENTAL'],
            ['minsal' => '575841', 'number' => '575841', 'visualization' => 'SALA 3 DENTAL THOMPSON', 'service' => 'DENTAL'],
            ['minsal' => '575842', 'number' => '575842', 'visualization' => 'SALA 4 DENTAL THOMPSON', 'service' => 'DENTAL'],
            ['minsal' => '575843', 'number' => '575843', 'visualization' => 'SALA 5 DENTAL THOMPSON', 'service' => 'DENTAL'],
            ['minsal' => '575844', 'number' => '575844', 'visualization' => 'PABELLON DENTAL', 'service' => 'DENTAL'],
            ['minsal' => '575845', 'number' => '575845', 'visualization' => 'URGENCIA DENTAL', 'service' => 'DENTAL'],
            ['minsal' => '575846', 'number' => '575846', 'visualization' => 'COORD. PROCUR. ORGANOS', 'service' => 'PROCURAMIENTO DE ORGANOS'],
            ['minsal' => '575847', 'number' => '575847', 'visualization' => 'ESTUDIO PRETRANSPLANTE', 'service' => 'PROCURAMIENTO DE ORGANOS'],
            ['minsal' => '575848', 'number' => '575848', 'visualization' => 'JEFE INFORMATICA', 'service' => 'TIC'],
            ['minsal' => '575849', 'number' => '575849', 'visualization' => 'AREA DESARROLLO 1', 'service' => 'TIC'],
            ['minsal' => '575850', 'number' => '575850', 'visualization' => 'AREA DESARROLLO 2', 'service' => 'TIC'],
            ['minsal' => '575851', 'number' => '575851', 'visualization' => 'Desarrollador 5', 'service' => 'TIC'],
            ['minsal' => '575852', 'number' => '575852', 'visualization' => 'AREA DESARROLLO 4', 'service' => 'TIC'],
            ['minsal' => '575853', 'number' => '575853', 'visualization' => 'TECNICO 1 INFORMATICA', 'service' => 'TIC'],
            ['minsal' => '575854', 'number' => '575854', 'visualization' => 'TECNICO 2 INFORMATICA', 'service' => 'TIC'],
            ['minsal' => '575855', 'number' => '575855', 'visualization' => 'TECNICO 3 INFORMATICA', 'service' => 'TIC'],
            ['minsal' => '575856', 'number' => '575856', 'visualization' => 'TECNICO 4 INFORMATICA', 'service' => 'TIC'],
            ['minsal' => '575857', 'number' => '575857', 'visualization' => 'SALA SERVIDOR', 'service' => 'TIC'],
            ['minsal' => '575858', 'number' => '575858', 'visualization' => 'Secretaria Informatica', 'service' => 'TIC'],
            ['minsal' => '575860', 'number' => '575860', 'visualization' => 'SECRETARIA DIRECTOR', 'service' => 'DIRECCION'],
            ['minsal' => '575861', 'number' => '575861', 'visualization' => 'SECRETARIA DIRECCION', 'service' => 'DIRECCION'],
            ['minsal' => '575863', 'number' => '575863', 'visualization' => 'contactabilidad 2', 'service' => 'CONTABILIDAD'],
            ['minsal' => '575865', 'number' => '575865', 'visualization' => 'OFICNA DE PARTE 2', 'service' => 'OFICINA DE PARTES'],
            ['minsal' => '575866', 'number' => '575866', 'visualization' => 'OFICINA DE PARTE 3', 'service' => 'OFICINA DE PARTES'],
            ['minsal' => '575867', 'number' => '575867', 'visualization' => 'OFICINA DE PARTE 4', 'service' => 'OFICINA DE PARTES'],
            ['minsal' => '575868', 'number' => '575868', 'visualization' => 'OFICINA DE PARTE 5', 'service' => 'OFICINA DE PARTES'],
            ['minsal' => '575869', 'number' => '575869', 'visualization' => 'MUSEO 1', 'service' => 'MUSEO'],
            ['minsal' => '575870', 'number' => '575870', 'visualization' => 'Salud Ocupacional', 'service' => 'SALUD OCUPACIONAL'],
            ['minsal' => '575871', 'number' => '575871', 'visualization' => 'ABOGADO', 'service' => 'ABOGADO'],
            ['minsal' => '575872', 'number' => '575872', 'visualization' => 'AUDITOR MEDICO', 'service' => 'AUDITORIA'],
            ['minsal' => '575873', 'number' => '575873', 'visualization' => 'AUDITOR ADMINISTRATIVO', 'service' => 'AUDITORIA'],
            ['minsal' => '575874', 'number' => '575874', 'visualization' => 'SALA DE SITUACIONES COE', 'service' => 'SALA COE'],
            ['minsal' => '575876', 'number' => '575876', 'visualization' => 'JEFE ENDOSCOPIA', 'service' => 'CAE ENDOSCOPIA'],
            ['minsal' => '575877', 'number' => '575877', 'visualization' => 'SECRETARIA ENDOSCOPIA', 'service' => 'CAE ENDOSCOPIA'],
            ['minsal' => '575878', 'number' => '575878', 'visualization' => 'SALA REUNION 1 ENDOSCOPIA', 'service' => 'CAE ENDOSCOPIA'],
            ['minsal' => '575879', 'number' => '575879', 'visualization' => 'SALA REUNION 2 ENDOSCOPIA', 'service' => 'CAE ENDOSCOPIA'],
            ['minsal' => '575880', 'number' => '575880', 'visualization' => 'PABELLON ENDOSCOPIA', 'service' => 'CAE ENDOSCOPIA'],
            ['minsal' => '575881', 'number' => '575881', 'visualization' => 'ENDOSCOPIA ENFERMERA GES', 'service' => 'CAE ENDOSCOPIA'],
            ['minsal' => '575883', 'number' => '575883', 'visualization' => 'coord.reclutamiento', 'service' => 'RECLUTAMIENTO'],
            ['minsal' => '575884', 'number' => '575884', 'visualization' => 'JEFE FARMACIA', 'service' => 'FARMACIA'],
            ['minsal' => '575885', 'number' => '575885', 'visualization' => 'SECRETARIA FARMACIA', 'service' => 'FARMACIA'],
            ['minsal' => '575886', 'number' => '575886', 'visualization' => 'Dispensacion Hospitalizados', 'service' => 'FARMACIA'],
            ['minsal' => '575887', 'number' => '575887', 'visualization' => 'Farmaceuticos Ambulatoria', 'service' => 'FARMACIA'],
            ['minsal' => '575888', 'number' => '575888', 'visualization' => 'DIGITADOR 2 FARMACIA', 'service' => 'FARMACIA'],
            ['minsal' => '575889', 'number' => '575889', 'visualization' => 'KARDEX FARMACIA', 'service' => 'FARMACIA'],
            ['minsal' => '575890', 'number' => '575890', 'visualization' => 'Quimico Farmaceutico', 'service' => 'FARMACIA'],
            ['minsal' => '575891', 'number' => '575891', 'visualization' => 'QUIMICO FARMACEUTICO', 'service' => 'FARMACIA'],
            ['minsal' => '575892', 'number' => '575892', 'visualization' => 'BODEGA PRINCIPAL FARMACIA', 'service' => 'FARMACIA'],
            ['minsal' => '575893', 'number' => '575893', 'visualization' => 'QUIMICO 1 FARMACIA', 'service' => 'FARMACIA'],
            ['minsal' => '575894', 'number' => '575894', 'visualization' => 'QUIMICO 2 FARMACIA', 'service' => 'FARMACIA'],
            ['minsal' => '575895', 'number' => '575895', 'visualization' => 'Cirugiaa Mayor Ambulatoria', 'service' => 'CMA'],
            ['minsal' => '575897', 'number' => '575897', 'visualization' => 'FARMACIA', 'service' => 'FARMACIA'],
            ['minsal' => '575898', 'number' => '575898', 'visualization' => 'DISPENSACION AMBULATORIA 2', 'service' => 'FARMACIA'],
            ['minsal' => '575899', 'number' => '575899', 'visualization' => 'DISPENSACION 1', 'service' => 'FARMACIA'],
            ['minsal' => '575900', 'number' => '575900', 'visualization' => 'DISPENSACION 2', 'service' => 'FARMACIA'],
            ['minsal' => '575901', 'number' => '575901', 'visualization' => 'MEY-LIN LAM M', 'service' => 'PRAIS'],
            ['minsal' => '575902', 'number' => '575902', 'visualization' => 'PALOMA LY S', 'service' => 'PRAIS'],
            ['minsal' => '575903', 'number' => '575903', 'visualization' => 'LUIS CORTES H', 'service' => 'PRAIS'],
            ['minsal' => '575904', 'number' => '575904', 'visualization' => 'GUARDERIA', 'service' => 'GUARDERIA'],
            ['minsal' => '575905', 'number' => '575905', 'visualization' => 'OFICINA 1 FENATS', 'service' => 'FENATS'],
            ['minsal' => '575906', 'number' => '575906', 'visualization' => 'OFICINA 2 FENATS', 'service' => 'FENATS'],
            ['minsal' => '575909', 'number' => '575909', 'visualization' => 'JEFE FINANZAS', 'service' => 'FINANZAS'],
            ['minsal' => '575911', 'number' => '575911', 'visualization' => 'JEFE CONTABILIDAD', 'service' => 'CONTABILIDAD'],
            ['minsal' => '575912', 'number' => '575912', 'visualization' => 'SECRETARIA 1 FINANZAS', 'service' => 'FINANZAS'],
            ['minsal' => '575913', 'number' => '575913', 'visualization' => 'COBRANZA PAGARE FINANZAS', 'service' => 'FINANZAS'],
            ['minsal' => '575914', 'number' => '575914', 'visualization' => 'CTA. CORRIENTE 1 FINANZAS', 'service' => 'FINANZAS'],
            ['minsal' => '575915', 'number' => '575915', 'visualization' => 'CTA. CORRIENTE 2 FINANZAS', 'service' => 'FINANZAS'],
            ['minsal' => '575916', 'number' => '575916', 'visualization' => 'BOLETINES FINANZAS', 'service' => 'FINANZAS'],
            ['minsal' => '575917', 'number' => '575917', 'visualization' => 'CAJA FINANZAS', 'service' => 'FINANZAS'],
            ['minsal' => '575918', 'number' => '575918', 'visualization' => 'PRES. INGRESO FINANZAS', 'service' => 'FINANZAS'],
            ['minsal' => '575919', 'number' => '575919', 'visualization' => 'PRE QX ENFERMERA', 'service' => 'PREQX'],
            ['minsal' => '575920', 'number' => '575920', 'visualization' => 'CIRUGIA MAXILOFACIAL', 'service' => 'MAXILOFACIAL'],
            ['minsal' => '575921', 'number' => '575921', 'visualization' => 'ANALISTA CONTABLE FINANZAS', 'service' => 'FINANZAS'],
            ['minsal' => '575922', 'number' => '575922', 'visualization' => 'RRFF unidad de inventario', 'service' => 'FINANZAS'],
            ['minsal' => '575923', 'number' => '575923', 'visualization' => 'SECRETARIA 2 FINANZAS', 'service' => 'FINANZAS'],
            ['minsal' => '575924', 'number' => '575924', 'visualization' => 'FENTES', 'service' => 'FENTES'],
            ['minsal' => '575925', 'number' => '575925', 'visualization' => 'FENPRUS', 'service' => 'FENPRUS'],
            ['minsal' => '575926', 'number' => '575926', 'visualization' => 'FENATSSI', 'service' => 'FENATSSI'],
            ['minsal' => '575927', 'number' => '575927', 'visualization' => 'JEFE MOVILIZACION', 'service' => 'MOVILIZACION'],
            ['minsal' => '575928', 'number' => '575928', 'visualization' => 'SECRETARIA DENTAL', 'service' => 'DENTAL'],
            ['minsal' => '575929', 'number' => '575929', 'visualization' => 'ESTAR MOVILIZACION', 'service' => 'MOVILIZACION'],
            ['minsal' => '575931', 'number' => '575931', 'visualization' => 'OPERADOR AMB.', 'service' => 'SAMU'],
            ['minsal' => '575932', 'number' => '575932', 'visualization' => 'ENF. SUPERV. C. ESTADIA', 'service' => 'PSIQUITRIA INFANTO'],
            ['minsal' => '575933', 'number' => '575933', 'visualization' => 'SECRETARIA C. ESTADIA', 'service' => 'PSIQUITRIA INFANTO'],
            ['minsal' => '575934', 'number' => '575934', 'visualization' => 'EST ENF. M. C. ESTADIA', 'service' => 'PSIQUITRIA INFANTO'],
            ['minsal' => '575935', 'number' => '575935', 'visualization' => 'SALA REUNION C. ESTADIA', 'service' => 'PSIQUITRIA INFANTO'],
            ['minsal' => '575936', 'number' => '575936', 'visualization' => 'RES. PERSONAL C. ESTADIA', 'service' => 'PSIQUITRIA INFANTO'],
            ['minsal' => '575937', 'number' => '575937', 'visualization' => 'BOX MED. M. C. ESTADIA', 'service' => 'PSIQUITRIA INFANTO'],
            ['minsal' => '575938', 'number' => '575938', 'visualization' => 'HALL CENTRAL C. ESTADIA', 'service' => 'PSIQUITRIA INFANTO'],
            ['minsal' => '575939', 'number' => '575939', 'visualization' => 'EST ENF. H. C. ESTADIA', 'service' => 'PSIQUITRIA INFANTO'],
            ['minsal' => '575940', 'number' => '575940', 'visualization' => 'COCINA CORTA ESTADIA', 'service' => 'PSIQUITRIA INFANTO'],
            ['minsal' => '575941', 'number' => '575941', 'visualization' => 'BOX MED. H. C. ESTADIA', 'service' => 'PSIQUITRIA INFANTO'],
            ['minsal' => '575942', 'number' => '575942', 'visualization' => 'SALA TERAPIA C. ESTADIA', 'service' => 'PSIQUITRIA INFANTO'],
            ['minsal' => '575944', 'number' => '575944', 'visualization' => 'FACILITADOR RURAL', 'service' => 'RURAL'],
            ['minsal' => '575945', 'number' => '575945', 'visualization' => 'Prog. Control Infecc', 'service' => 'INFECTOLOGIA'],
            ['minsal' => '575946', 'number' => '575946', 'visualization' => 'GRD', 'service' => 'GRD'],
            ['minsal' => '575947', 'number' => '575947', 'visualization' => 'Oficina Asesor Juridico', 'service' => 'JURIDICA'],
            ['minsal' => '575948', 'number' => '575948', 'visualization' => 'SALA COMITE ONCOLOGICO', 'service' => 'ONCOLOGIA'],
            ['minsal' => '575949', 'number' => '575949', 'visualization' => 'JEFE JARDIN INFANTIL', 'service' => 'JARDIN'],
            ['minsal' => '575950', 'number' => '575950', 'visualization' => 'SECRETARIA J. INFANTIL', 'service' => 'JARDIN'],
            ['minsal' => '575951', 'number' => '575951', 'visualization' => 'SALA CUNA MENOR', 'service' => 'JARDIN'],
            ['minsal' => '575952', 'number' => '575952', 'visualization' => 'SALA JUEGOS', 'service' => 'JARDIN'],
            ['minsal' => '575953', 'number' => '575953', 'visualization' => 'SALA CUNA MAYOR', 'service' => 'JARDIN'],
            ['minsal' => '575954', 'number' => '575954', 'visualization' => 'MEDIO MENOR', 'service' => 'JARDIN'],
            ['minsal' => '575955', 'number' => '575955', 'visualization' => 'MEDIO MAYOR', 'service' => 'JARDIN'],
            ['minsal' => '575956', 'number' => '575956', 'visualization' => 'TRANSICION I', 'service' => 'JARDIN'],
            ['minsal' => '575957', 'number' => '575957', 'visualization' => 'SALA 2 TRANSICION II', 'service' => 'JARDIN'],
            ['minsal' => '575958', 'number' => '575958', 'visualization' => 'SALA 1 TRANSICION II', 'service' => 'JARDIN'],
            ['minsal' => '575959', 'number' => '575959', 'visualization' => 'SALA COMP. J. INFANTIL', 'service' => 'JARDIN'],
            ['minsal' => '575960', 'number' => '575960', 'visualization' => 'JEFA DOCENCIA', 'service' => 'DOCENCIA'],
            ['minsal' => '575961', 'number' => '575961', 'visualization' => 'Gestion de Equipos', 'service' => 'Equipos'],
            ['minsal' => '575962', 'number' => '575962', 'visualization' => 'JEFE KINESIOLOGIA', 'service' => 'JEFE'],
            ['minsal' => '575963', 'number' => '575963', 'visualization' => 'RECEPCION KINE', 'service' => 'CAE KINESIOLOGIA'],
            ['minsal' => '575964', 'number' => '575964', 'visualization' => 'KINESIOLOGO GES', 'service' => 'KINES MATRONA'],
            ['minsal' => '575965', 'number' => '575965', 'visualization' => 'GIMNASIO 1 KINE.', 'service' => 'GIMNASIO'],
            ['minsal' => '575966', 'number' => '575966', 'visualization' => 'PRQX ENFERMERA 1', 'service' => 'PREQX'],
            ['minsal' => '575967', 'number' => '575967', 'visualization' => 'TERAPIA OCUPACIONAL', 'service' => 'TERAPIA OCUPACIONAL'],
            ['minsal' => '575968', 'number' => '575968', 'visualization' => 'AT. PACIENTES KINE', 'service' => 'CAE KINESIOLOGIA'],
            ['minsal' => '575969', 'number' => '575969', 'visualization' => 'PASILLO KINE.', 'service' => 'CAE KINESIOLOGIA'],
            ['minsal' => '575972', 'number' => '575972', 'visualization' => 'JEFE LABORATORIO', 'service' => 'LABORATORIO'],
            ['minsal' => '575973', 'number' => '575973', 'visualization' => 'SECREATARIO LAB.', 'service' => 'LABORATORIO'],
            ['minsal' => '575974', 'number' => '575974', 'visualization' => 'RECEPCION 2 LAB.', 'service' => 'LABORATORIO'],
            ['minsal' => '575975', 'number' => '575975', 'visualization' => 'URGENCIA LAB.', 'service' => 'LABORATORIO'],
            ['minsal' => '575976', 'number' => '575976', 'visualization' => 'BODEGA DE INSUMOS LAB.', 'service' => 'LABORATORIO'],
            ['minsal' => '575977', 'number' => '575977', 'visualization' => 'LAB. QUIMICA 1', 'service' => 'LABORATORIO'],
            ['minsal' => '575978', 'number' => '575978', 'visualization' => 'LAB. QUIMICA 2', 'service' => 'LABORATORIO'],
            ['minsal' => '575979', 'number' => '575979', 'visualization' => 'BACTERIOLOGIA', 'service' => 'LABORATORIO'],
            ['minsal' => '575980', 'number' => '575980', 'visualization' => 'MICOBACTERIAS', 'service' => 'LABORATORIO'],
            ['minsal' => '575981', 'number' => '575981', 'visualization' => 'TOMA MUESTRAS 1 LAB.', 'service' => 'LABORATORIO'],
            ['minsal' => '575982', 'number' => '575982', 'visualization' => 'REPARAC. EQUIPOS', 'service' => 'LABORATORIO'],
            ['minsal' => '575983', 'number' => '575983', 'visualization' => 'TECNOLOGO GES OTORRINO', 'service' => 'LABORATORIO'],
            ['minsal' => '575984', 'number' => '575984', 'visualization' => 'INFECTOLOGIA', 'service' => 'LABORATORIO'],
            ['minsal' => '575985', 'number' => '575985', 'visualization' => 'HEMATOLOGIA 2', 'service' => 'LABORATORIO'],
            ['minsal' => '575986', 'number' => '575986', 'visualization' => 'HEMATOLOGIA 3', 'service' => 'LABORATORIO'],
            ['minsal' => '575987', 'number' => '575987', 'visualization' => 'RESIDENCIA 1 LAB.', 'service' => 'LABORATORIO'],
            ['minsal' => '575988', 'number' => '575988', 'visualization' => 'RESIDENCIA 2 LAB.', 'service' => 'LABORATORIO'],
            ['minsal' => '575989', 'number' => '575989', 'visualization' => 'SALA REUNION LAB.', 'service' => 'LABORATORIO'],
            ['minsal' => '575990', 'number' => '575990', 'visualization' => 'BOX MATRONA ITS', 'service' => 'LABORATORIO'],
            ['minsal' => '575991', 'number' => '575991', 'visualization' => 'SEROLOGIA', 'service' => 'LABORATORIO'],
            ['minsal' => '575992', 'number' => '575992', 'visualization' => 'Of. Calidad', 'service' => 'OFICINA DE CALIDAD'],
            ['minsal' => '575993', 'number' => '575993', 'visualization' => 'T.S Rosa Encina', 'service' => 'SOME'],
            ['minsal' => '575994', 'number' => '575994', 'visualization' => 'INMUNOLOGIA', 'service' => 'LABORATORIO'],
            ['minsal' => '575997', 'number' => '575997', 'visualization' => 'CX PLASTICA Y QUEMADOS', 'service' => 'CIRUGIA PLASTICA'],
            ['minsal' => '575999', 'number' => '575999', 'visualization' => 'fenats regional', 'service' => 'FENAT'],
            ['minsal' => '576003', 'number' => '576003', 'visualization' => 'Epidemiologia', 'service' => 'EPIDEMIOLOGIA'],
            ['minsal' => '576004', 'number' => '576004', 'visualization' => 'Vanessa Sepulveda', 'service' => 'SSI'],
            ['minsal' => '576005', 'number' => '576005', 'visualization' => 'Franco Petrillo', 'service' => 'SSI'],
            ['minsal' => '576006', 'number' => '576006', 'visualization' => 'Blanca Galaz', 'service' => 'SSI'],
            ['minsal' => '576030', 'number' => '576030', 'visualization' => 'Club Escolar', 'service' => 'CENTRO ESCOLAR'],
            ['minsal' => '576031', 'number' => '576031', 'visualization' => 'Paramedico VIH', 'service' => 'VIH'],
            ['minsal' => '576032', 'number' => '576032', 'visualization' => 'Medico VIH', 'service' => 'VIH'],
            ['minsal' => '576033', 'number' => '576033', 'visualization' => 'Matrona VIH', 'service' => 'VIH'],
            ['minsal' => '576035', 'number' => '576035', 'visualization' => 'Pre Quirurgico 1', 'service' => 'PREQX'],
            ['minsal' => '576036', 'number' => '576036', 'visualization' => 'Pre Quirurgico 2', 'service' => 'PREQX'],
            ['minsal' => '576037', 'number' => '576037', 'visualization' => 'Secretaria UTI', 'service' => 'UPCA'],
            ['minsal' => '576038', 'number' => '576038', 'visualization' => 'Oficina Calidad 2', 'service' => 'OFICINA DE CALIDAD'],
            ['minsal' => '576039', 'number' => '576039', 'visualization' => 'Dario Astudillo', 'service' => 'SSI'],
            ['minsal' => '576043', 'number' => '576043', 'visualization' => 'PAGARE', 'service' => 'RECAUDACION'],
            ['minsal' => '576046', 'number' => '576046', 'visualization' => 'EPIDEMIOLOGIA', 'service' => 'EPIDEMIOLOGIA'],
            ['minsal' => '576047', 'number' => '576047', 'visualization' => 'EPIDEMIOLOGIA', 'service' => 'EPIDEMIOLOGIA'],
            ['minsal' => '576048', 'number' => '576048', 'visualization' => 'Salud del trabajador', 'service' => 'SALUD DE TRABAJADOR'],
            ['minsal' => '576049', 'number' => '576049', 'visualization' => 'reclutamiento y seleccion 1', 'service' => 'RECLUTAMIENTO'],
            ['minsal' => '576052', 'number' => '576052', 'visualization' => 'HOSPITALIZACION DOMICILIARIA', 'service' => 'HOSPITALIZACION DOMICILIARIA'],
            ['minsal' => '576053', 'number' => '576053', 'visualization' => 'FARMACIA SALUD MENTAL', 'service' => 'FARMCIA COSAM'],
            ['minsal' => '576054', 'number' => '576054', 'visualization' => 'Honorarios', 'service' => 'PERSONAL'],
            ['minsal' => '576057', 'number' => '576057', 'visualization' => 'Coordinador Sirh', 'service' => 'PERSONAL'],
            ['minsal' => '576059', 'number' => '576059', 'visualization' => 'Jefatura de Calidad', 'service' => 'CALIDAD'],
            ['minsal' => '576060', 'number' => '576060', 'visualization' => 'HPT IQUIQUE', 'service' => 'IQUIQUE'],
            ['minsal' => '576062', 'number' => '576062', 'visualization' => 'HPT IQUIQUE', 'service' => 'HPT I MATRONA'],
            ['minsal' => '576063', 'number' => '576063', 'visualization' => 'Gestion de Cama', 'service' => 'GESTION DE CAMA'],
            ['minsal' => '576064', 'number' => '576064', 'visualization' => 'Gestion de Cama', 'service' => 'GESTION DE CAMA'],
            ['minsal' => '576065', 'number' => '576065', 'visualization' => 'Gestion de Cama', 'service' => 'GESTION DE CAMA'],
            ['minsal' => '576067', 'number' => '576067', 'visualization' => 'UGCC', 'service' => 'GESTION DE CAMA'],
            ['minsal' => '576068', 'number' => '576068', 'visualization' => 'UNIDAD DE GESTION DE CAMA', 'service' => 'GESTION DE CAMA'],
            ['minsal' => '576069', 'number' => '576069', 'visualization' => 'Mantencion', 'service' => 'MANTENCION'],
            ['minsal' => '576071', 'number' => '576071', 'visualization' => 'psiquiatria of. Orientadores', 'service' => 'PSIQUIATRIA'],
            ['minsal' => '576358', 'number' => '576358', 'visualization' => 'ENFERM SUPVRA PSIQ', 'service' => 'PSIQUIATRIA'],
            ['minsal' => '576380', 'number' => '576380', 'visualization' => 'SECRETARIA CMA', 'service' => 'CMA'],
            ['minsal' => '576401', 'number' => '576401', 'visualization' => 'JEFATURA INVENTARIO', 'service' => 'INVENTARIO'],
            ['minsal' => '576402', 'number' => '576402', 'visualization' => 'SUPERVISORA MATRONERIA', 'service' => 'SUPER MATRONA'],
            ['minsal' => '576403', 'number' => '576403', 'visualization' => 'OF. ADMISION SOME', 'service' => 'SOME'],
            ['minsal' => '576404', 'number' => '576404', 'visualization' => 'OF. AGENDA MEDICA SOME', 'service' => 'SOME'],
            ['minsal' => '576405', 'number' => '576405', 'visualization' => 'OF. TRASLADO 1 SOME', 'service' => 'SOME'],
            ['minsal' => '576407', 'number' => '576407', 'visualization' => 'DORIS CONDORI', 'service' => 'SOME'],
            ['minsal' => '576408', 'number' => '576408', 'visualization' => 'JEFE SOME', 'service' => 'SOME'],
            ['minsal' => '576410', 'number' => '576410', 'visualization' => 'OF. RED ASISTENCIAL 4 SOME', 'service' => 'SOME'],
            ['minsal' => '576411', 'number' => '576411', 'visualization' => 'JEFE RECAUDACION', 'service' => 'RECAUDACION'],
            ['minsal' => '576412', 'number' => '576412', 'visualization' => 'TESORERIA SOME', 'service' => 'RECAUDACION'],
            ['minsal' => '576413', 'number' => '576413', 'visualization' => 'CAJA', 'service' => 'RECAUDACION'],
            ['minsal' => '576414', 'number' => '576414', 'visualization' => 'RECAUDACION URGENCIA 1', 'service' => 'RECAUDACION'],
            ['minsal' => '576415', 'number' => '576415', 'visualization' => 'RECAUDACION URGENCIA 2', 'service' => 'RECAUDACION'],
            ['minsal' => '576416', 'number' => '576416', 'visualization' => 'Matrona Alto Riesgo', 'service' => 'CAE GINECOLOGIA'],
            ['minsal' => '576417', 'number' => '576417', 'visualization' => 'RECAUDACION SOME', 'service' => 'RECAUDACION'],
            ['minsal' => '576418', 'number' => '576418', 'visualization' => 'DISPENSACION AMBULATORIA 1', 'service' => 'FARMACIA'],
            ['minsal' => '576419', 'number' => '576419', 'visualization' => 'VENTANILLA CITAS 3 SOME', 'service' => 'SOME'],
            ['minsal' => '576420', 'number' => '576420', 'visualization' => 'VENTANILLA CITAS 4 SOME', 'service' => 'SOME'],
            ['minsal' => '576421', 'number' => '576421', 'visualization' => 'VENTANILLA 1 P. AMARILLO SOME', 'service' => 'SOME'],
            ['minsal' => '576422', 'number' => '576422', 'visualization' => 'LICITACION MANTENCION', 'service' => 'MANTENCION'],
            ['minsal' => '576423', 'number' => '576423', 'visualization' => 'VENTANILLA 3 P. AMARILLO SOME', 'service' => 'SOME'],
            ['minsal' => '576424', 'number' => '576424', 'visualization' => 'presupuesto y gastos 1', 'service' => 'RECAUDACION'],
            ['minsal' => '576425', 'number' => '576425', 'visualization' => 'EU TRASLADO', 'service' => 'SOME'],
            ['minsal' => '576426', 'number' => '576426', 'visualization' => 'ASIST. SOCIAL SOME', 'service' => 'SOME'],
            ['minsal' => '576427', 'number' => '576427', 'visualization' => 'ASISTENTE SOCIAL 2 SOME', 'service' => 'SOME'],
            ['minsal' => '576428', 'number' => '576428', 'visualization' => 'ENCARGADO ARCHIVO', 'service' => 'ARCHIVO'],
            ['minsal' => '576429', 'number' => '576429', 'visualization' => 'ARCHIVO 1', 'service' => 'ARCHIVO'],
            ['minsal' => '576430', 'number' => '576430', 'visualization' => 'Secretaria Traslado', 'service' => 'SOME'],
            ['minsal' => '576431', 'number' => '576431', 'visualization' => 'ARCHIVO 3', 'service' => 'ARCHIVO'],
            ['minsal' => '576432', 'number' => '576432', 'visualization' => 'ARCHIVO PASIVO 1', 'service' => 'ARCHIVO'],
            ['minsal' => '576433', 'number' => '576433', 'visualization' => 'ARCHIVO PASIVO 2', 'service' => 'ARCHIVO'],
            ['minsal' => '576434', 'number' => '576434', 'visualization' => 'FACILITADORA RURAL', 'service' => 'RURAL'],
            ['minsal' => '576436', 'number' => '576436', 'visualization' => 'lista espera consulta', 'service' => 'SOME'],
            ['minsal' => '576437', 'number' => '576437', 'visualization' => 'T.S. Jose Olivares', 'service' => 'SOME'],
            ['minsal' => '576438', 'number' => '576438', 'visualization' => 'MATRONA COORDINADORA', 'service' => 'COORDINADORA MATRONERIA'],
            ['minsal' => '576439', 'number' => '576439', 'visualization' => 'SUBDIRECTOR OPERACIONES', 'service' => 'OPERACIONES'],
            ['minsal' => '576441', 'number' => '576441', 'visualization' => 'Gremio Auxiliares', 'service' => 'GREMIO AUX'],
            ['minsal' => '576442', 'number' => '576442', 'visualization' => 'COMITE HOSP AMIGABLE', 'service' => 'COMITE HOSP AMIGABLE'],
            ['minsal' => '576443', 'number' => '576443', 'visualization' => 'OFICINA CALIDAD', 'service' => 'OFICINA DE CALIDAD'],
            ['minsal' => '576444', 'number' => '576444', 'visualization' => 'CAROLINA VILLARROEL', 'service' => 'SOME'],
            ['minsal' => '576445', 'number' => '576445', 'visualization' => 'GREMIO TENS', 'service' => 'GREMIO AUX'],
            ['minsal' => '576446', 'number' => '576446', 'visualization' => 'HOSPITALIZACION DOMICILIARIA', 'service' => 'HOSPITALIZACION DOMICILIARIA'],
            ['minsal' => '576448', 'number' => '576448', 'visualization' => 'Recaudación Hospitalizada', 'service' => 'RECAUDACION'],
            ['minsal' => '576450', 'number' => '576450', 'visualization' => 'Urgencia Hospitalizada 1', 'service' => 'RECAUDACION'],
            ['minsal' => '576451', 'number' => '576451', 'visualization' => 'Urgencia Hospitalizada 2', 'service' => 'RECAUDACION'],
            ['minsal' => '576452', 'number' => '576452', 'visualization' => 'Urgencia Hospitalizada 3', 'service' => 'RECAUDACION'],
            ['minsal' => '576453', 'number' => '576453', 'visualization' => 'Urgencia Hospitalizada 4', 'service' => 'RECAUDACION'],
            ['minsal' => '576454', 'number' => '576454', 'visualization' => 'Urgencia Hospitalizada 5', 'service' => 'RECAUDACION'],
            ['minsal' => '576455', 'number' => '576455', 'visualization' => 'Urgencia Hospitalizada 6', 'service' => 'RECAUDACION'],
            ['minsal' => '576456', 'number' => '576456', 'visualization' => 'Urgencia Hospitalizada 7', 'service' => 'RECAUDACION'],
            ['minsal' => '576457', 'number' => '576457', 'visualization' => 'Urgencia Hospitalizada 8', 'service' => 'RECAUDACION'],
            ['minsal' => '576458', 'number' => '576458', 'visualization' => 'Urgencia Hospitalizada 9', 'service' => 'RECAUDACION'],
            ['minsal' => '576459', 'number' => '576459', 'visualization' => 'Urgencia Hospitalizada 10', 'service' => 'RECAUDACION'],
            ['minsal' => '576461', 'number' => '576461', 'visualization' => 'CAJA RECAUDACION', 'service' => 'RECAUDACION'],
            ['minsal' => '576463', 'number' => '576463', 'visualization' => 'CAJA RECAUDACION', 'service' => 'RECAUDACION'],
            ['minsal' => '576464', 'number' => '576464', 'visualization' => 'CAJA RECAUDACION', 'service' => 'RECAUDACION'],
            ['minsal' => '576466', 'number' => '576466', 'visualization' => 'OF. ADMISION OPIST', 'service' => 'OPIST'],
            ['minsal' => '576468', 'number' => '576468', 'visualization' => 'OF. CONTROL ASISTENCIAL', 'service' => 'OPIST'],
            ['minsal' => '576469', 'number' => '576469', 'visualization' => 'OF. TECNICA CONTROL 1', 'service' => 'OPIST'],
            ['minsal' => '576471', 'number' => '576471', 'visualization' => 'CAJA 1 TOMA DE MUESTRA', 'service' => 'OPIST'],
            ['minsal' => '576472', 'number' => '576472', 'visualization' => 'OF. TRASLADO 2 SOME', 'service' => 'SOME'],
            ['minsal' => '576473', 'number' => '576473', 'visualization' => 'GREMIO SUPERVISORES', 'service' => 'GREMIO SUP'],
            ['minsal' => '576474', 'number' => '576474', 'visualization' => 'VENTANILLA CITAS 2 SOME', 'service' => 'SOME'],
            ['minsal' => '576475', 'number' => '576475', 'visualization' => 'GREMIO TENS', 'service' => 'GREMIO TENS'],
            ['minsal' => '576476', 'number' => '576476', 'visualization' => 'DCTO. CIRUGIA', 'service' => 'CIRUGIA'],
            ['minsal' => '576477', 'number' => '576477', 'visualization' => 'Esterilización 1', 'service' => 'Esterilización'],
            ['minsal' => '576478', 'number' => '576478', 'visualization' => 'DCTO. HEMODIALISIS', 'service' => 'HEMODIALISIS'],
            ['minsal' => '576479', 'number' => '576479', 'visualization' => 'Lista de Espera', 'service' => 'SOME'],
            ['minsal' => '576480', 'number' => '576480', 'visualization' => 'Hospitalizacion Quirofano', 'service' => 'QUIROFANO'],
            ['minsal' => '576481', 'number' => '576481', 'visualization' => 'Medicina Transfusional', 'service' => 'HEMODIALISIS'],
            ['minsal' => '576482', 'number' => '576482', 'visualization' => 'QUIROFANO', 'service' => 'QUIROFANO'],
            ['minsal' => '576483', 'number' => '576483', 'visualization' => 'LABORATORIO', 'service' => 'LABORATORIO'],
            ['minsal' => '576484', 'number' => '576484', 'visualization' => 'QUIROFANO', 'service' => 'QUIROFANO'],
            ['minsal' => '576485', 'number' => '576485', 'visualization' => 'Medicina Transfusional', 'service' => 'QUIROFANO'],
            ['minsal' => '576487', 'number' => '576487', 'visualization' => 'CONCILIACION PREQUIRURGICA', 'service' => 'QUIROFANO'],
            ['minsal' => '576489', 'number' => '576489', 'visualization' => 'Esterilización', 'service' => 'Esterilización'],
            ['minsal' => '576490', 'number' => '576490', 'visualization' => 'Matroneria 1 QUIROFANO', 'service' => 'QUIROFANO'],
            ['minsal' => '576491', 'number' => '576491', 'visualization' => 'Matroneria 2 QUIROFANO', 'service' => 'QUIROFANO'],
            ['minsal' => '576493', 'number' => '576493', 'visualization' => 'Matroneria 3 QUIROFANO', 'service' => 'QUIROFANO'],
            ['minsal' => '576494', 'number' => '576494', 'visualization' => 'Matroneria 4 QUIROFANO', 'service' => 'QUIROFANO'],
            ['minsal' => '576495', 'number' => '576495', 'visualization' => 'SOME CONSULTA', 'service' => 'SOME'],
            ['minsal' => '576497', 'number' => '576497', 'visualization' => 'SOME PRE OPERATORIO 1', 'service' => 'PREQX'],
            ['minsal' => '576498', 'number' => '576498', 'visualization' => 'SOME PRE OPERATORIO 2', 'service' => 'PREQX'],
            ['minsal' => '576499', 'number' => '576499', 'visualization' => 'SOME PRE OPERATORIO 3', 'service' => 'PREQX'],
            ['minsal' => '576500', 'number' => '576500', 'visualization' => 'SOME PRE OPERATORIO 4', 'service' => 'PREQX'],
            ['minsal' => '576501', 'number' => '576501', 'visualization' => 'SOME PRE OPERATORIO 5', 'service' => 'PREQX'],
            ['minsal' => '576503', 'number' => '576503', 'visualization' => 'SOME PRE OPERATORIO 6', 'service' => 'PREQX'],
            ['minsal' => '576504', 'number' => '576504', 'visualization' => 'CIRUGIA', 'service' => 'CIRUGIA'],
            ['minsal' => '576505', 'number' => '576505', 'visualization' => 'OF. TRASLADO', 'service' => 'SOME'],
            ['minsal' => '576506', 'number' => '576506', 'visualization' => 'OF. CITAS ESPECIALES', 'service' => 'SOME'],
            ['minsal' => '576507', 'number' => '576507', 'visualization' => 'TELEFONO 1 LABORATORIO', 'service' => 'LABORATORIO'],
            ['minsal' => '576508', 'number' => '576508', 'visualization' => 'TELEFONO 2 LABORATORIO', 'service' => 'LABORATORIO'],
            ['minsal' => '576509', 'number' => '576509', 'visualization' => 'TELEFONO 3 LABORATORIO', 'service' => 'LABORATORIO'],
            ['minsal' => '576510', 'number' => '576510', 'visualization' => 'TELEFONO 4 LABORATORIO', 'service' => 'LABORATORIO'],
            ['minsal' => '576511', 'number' => '576511', 'visualization' => 'TELEFONO 5 LABORATORIO', 'service' => 'LABORATORIO'],
            ['minsal' => '576512', 'number' => '576512', 'visualization' => 'TELEFONO 6 LABORATORIO', 'service' => 'LABORATORIO'],
            ['minsal' => '576514', 'number' => '576514', 'visualization' => 'Ventanilla 2 Farmacia SOM', 'service' => 'SOME'],
            ['minsal' => '576515', 'number' => '576515', 'visualization' => 'Pabellon 1', 'service' => 'QUIROFANO'],
            ['minsal' => '576516', 'number' => '576516', 'visualization' => 'Pabellon 2', 'service' => 'QUIROFANO'],
            ['minsal' => '576517', 'number' => '576517', 'visualization' => 'Pabellon 3', 'service' => 'QUIROFANO'],
            ['minsal' => '576518', 'number' => '576518', 'visualization' => 'Pabellon 4', 'service' => 'QUIROFANO'],
            ['minsal' => '576519', 'number' => '576519', 'visualization' => 'Pabellon 5', 'service' => 'QUIROFANO'],
            ['minsal' => '576520', 'number' => '576520', 'visualization' => 'Pabellon 6', 'service' => 'QUIROFANO'],
            ['minsal' => '576521', 'number' => '576521', 'visualization' => 'Pabellon 7', 'service' => 'QUIROFANO'],
            ['minsal' => '576523', 'number' => '576523', 'visualization' => 'Pabellon 8', 'service' => 'QUIROFANO'],
            ['minsal' => '576524', 'number' => '576524', 'visualization' => 'Matroneria 1 Parto', 'service' => 'QUIROFANO'],
            ['minsal' => '576525', 'number' => '576525', 'visualization' => 'Matroneria 2 Parto', 'service' => 'QUIROFANO'],
            ['minsal' => '576526', 'number' => '576526', 'visualization' => 'Matroneria 3 Parto', 'service' => 'QUIROFANO'],
            ['minsal' => '576527', 'number' => '576527', 'visualization' => 'Matroneria 4 Parto', 'service' => 'QUIROFANO'],
            ['minsal' => '576528', 'number' => '576528', 'visualization' => 'SOME PARTO', 'service' => 'SOME'],
            ['minsal' => '576530', 'number' => '576530', 'visualization' => 'Pabellon 9', 'service' => 'QUIROFANO'],
            ['minsal' => '576531', 'number' => '576531', 'visualization' => 'Pabellon 10', 'service' => 'QUIROFANO'],
            ['minsal' => '576533', 'number' => '576533', 'visualization' => 'Pabellon 11', 'service' => 'QUIROFANO'],
            ['minsal' => '576535', 'number' => '576535', 'visualization' => 'LABORATORIO', 'service' => 'LABORATORIO'],
            ['minsal' => '576536', 'number' => '576536', 'visualization' => 'LABORATORIO', 'service' => 'LABORATORIO'],
            ['minsal' => '576537', 'number' => '576537', 'visualization' => 'LABORATORIO', 'service' => 'LABORATORIO'],
            ['minsal' => '576538', 'number' => '576538', 'visualization' => 'LABORATORIO', 'service' => 'LABORATORIO'],
            ['minsal' => '576540', 'number' => '576540', 'visualization' => 'SOME', 'service' => 'SOME'],
            ['minsal' => '576542', 'number' => '576542', 'visualization' => 'Pabellon 12', 'service' => 'QUIROFANO'],
            ['minsal' => '576543', 'number' => '576543', 'visualization' => 'Farmacia 1 Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576544', 'number' => '576544', 'visualization' => 'Farmacia 2 Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576545', 'number' => '576545', 'visualization' => 'Esterilización 2', 'service' => 'QUIROFANO'],
            ['minsal' => '576546', 'number' => '576546', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576548', 'number' => '576548', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576549', 'number' => '576549', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576550', 'number' => '576550', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576551', 'number' => '576551', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576552', 'number' => '576552', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576553', 'number' => '576553', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576554', 'number' => '576554', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576556', 'number' => '576556', 'visualization' => 'OF. CITAS ESPECIALES', 'service' => 'SOME'],
            ['minsal' => '576558', 'number' => '576558', 'visualization' => 'OF. TRASLADO', 'service' => 'SOME'],
            ['minsal' => '576560', 'number' => '576560', 'visualization' => 'OF. CITAS ESPECIALES', 'service' => 'SOME'],
            ['minsal' => '576562', 'number' => '576562', 'visualization' => 'SOME CITAS', 'service' => 'SOME'],
            ['minsal' => '576564', 'number' => '576564', 'visualization' => 'Esterilización', 'service' => 'QUIROFANO'],
            ['minsal' => '576565', 'number' => '576565', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576566', 'number' => '576566', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576567', 'number' => '576567', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576568', 'number' => '576568', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576569', 'number' => '576569', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576570', 'number' => '576570', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576571', 'number' => '576571', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576572', 'number' => '576572', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576573', 'number' => '576573', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576574', 'number' => '576574', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576575', 'number' => '576575', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576576', 'number' => '576576', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576577', 'number' => '576577', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576579', 'number' => '576579', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576580', 'number' => '576580', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576581', 'number' => '576581', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576582', 'number' => '576582', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576583', 'number' => '576583', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576585', 'number' => '576585', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576586', 'number' => '576586', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576587', 'number' => '576587', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576588', 'number' => '576588', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576589', 'number' => '576589', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576590', 'number' => '576590', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576591', 'number' => '576591', 'visualization' => 'Farmacia Lab Clinico', 'service' => 'LABORATORIO'],
            ['minsal' => '576592', 'number' => '576592', 'visualization' => 'Farmacia Pabellón', 'service' => 'QUIROFANO'],
            ['minsal' => '576594', 'number' => '576594', 'visualization' => 'OF. TRASLADO', 'service' => 'SOME'],
            ['minsal' => '576596', 'number' => '576596', 'visualization' => 'TELEFONO 1 SOME', 'service' => 'SOME'],
            ['minsal' => '576598', 'number' => '576598', 'visualization' => 'TELEFONO 2 SOME', 'service' => 'SOME'],
            ['minsal' => '576600', 'number' => '576600', 'visualization' => 'TELEFONO 3 SOME', 'service' => 'SOME'],
            ['minsal' => '576602', 'number' => '576602', 'visualization' => 'TELEFONO 4 SOME', 'service' => 'SOME'],
            ['minsal' => '576604', 'number' => '576604', 'visualization' => 'TELEFONO 5 SOME', 'service' => 'SOME'],
            ['minsal' => '576606', 'number' => '576606', 'visualization' => 'TELEFONO 6 SOME', 'service' => 'SOME'],
            ['minsal' => '576608', 'number' => '576608', 'visualization' => 'TELEFONO 7 SOME', 'service' => 'SOME'],
            ['minsal' => '576610', 'number' => '576610', 'visualization' => 'TELEFONO 8 SOME', 'service' => 'SOME'],
            ['minsal' => '576612', 'number' => '576612', 'visualization' => 'TELEFONO 9 SOME', 'service' => 'SOME'],
            ['minsal' => '576614', 'number' => '576614', 'visualization' => 'TELEFONO 10 SOME', 'service' => 'SOME'],
            ['minsal' => '576616', 'number' => '576616', 'visualization' => 'TELEFONO 11 SOME', 'service' => 'SOME'],
            ['minsal' => '576618', 'number' => '576618', 'visualization' => 'TELEFONO 12 SOME', 'service' => 'SOME'],
            ['minsal' => '576620', 'number' => '576620', 'visualization' => 'TELEFONO 13 SOME', 'service' => 'SOME'],
            ['minsal' => '576622', 'number' => '576622', 'visualization' => 'TELEFONO 14 SOME', 'service' => 'SOME'],
            ['minsal' => '576624', 'number' => '576624', 'visualization' => 'TELEFONO 15 SOME', 'service' => 'SOME'],
            ['minsal' => '576626', 'number' => '576626', 'visualization' => 'TELEFONO 16 SOME', 'service' => 'SOME'],
            ['minsal' => '576628', 'number' => '576628', 'visualization' => 'TELEFONO 17 SOME', 'service' => 'SOME'],
            ['minsal' => '576630', 'number' => '576630', 'visualization' => 'TELEFONO 18 SOME', 'service' => 'SOME'],
            ['minsal' => '576632', 'number' => '576632', 'visualization' => 'TELEFONO 19 SOME', 'service' => 'SOME'],
            ['minsal' => '576634', 'number' => '576634', 'visualization' => 'TELEFONO 20 SOME', 'service' => 'SOME'],
            ['minsal' => '576636', 'number' => '576636', 'visualization' => 'TELEFONO 21 SOME', 'service' => 'SOME'],
            ['minsal' => '576638', 'number' => '576638', 'visualization' => 'TELEFONO 22 SOME', 'service' => 'SOME'],
            ['minsal' => '576640', 'number' => '576640', 'visualization' => 'TELEFONO 23 SOME', 'service' => 'SOME'],
            ['minsal' => '576642', 'number' => '576642', 'visualization' => 'TELEFONO 24 SOME', 'service' => 'SOME'],
            ['minsal' => '576644', 'number' => '576644', 'visualization' => 'TELEFONO 25 SOME', 'service' => 'SOME'],
            ['minsal' => '576646', 'number' => '576646', 'visualization' => 'TELEFONO 26 SOME', 'service' => 'SOME'],
            ['minsal' => '576648', 'number' => '576648', 'visualization' => 'TELEFONO 27 SOME', 'service' => 'SOME'],
            ['minsal' => '576650', 'number' => '576650', 'visualization' => 'TELEFONO 28 SOME', 'service' => 'SOME'],
            ['minsal' => '576652', 'number' => '576652', 'visualization' => 'TELEFONO 29 SOME', 'service' => 'SOME'],
            ['minsal' => '576654', 'number' => '576654', 'visualization' => 'TELEFONO 30 SOME', 'service' => 'SOME'],
        ];

        // insert data
        // Telephone::insert(array_map(function($telephone) {
        //     return [
        //         'minsal' => $telephone['minsal'],
        //         'number' => $telephone['number'],
        //         'visualization' => $telephone['visualization'],
        //         'service' => $telephone['service'],
        //     ];
        // }, $telephones));
    }
}
