<?php

namespace App\Http\Livewire\RequestForm\Item;

use App\Models\Parameters\UnitOfMeasurement;
use Livewire\Component;
use Livewire\WithFileUploads;

class RequestFormItems extends Component
{
    use WithFileUploads;

    public $article, $unitOfMeasurement, $technicalSpecifications, $quantity, $articleFile, $editRF, $savedItems, $deletedItems,
            $unitValue, $taxes, $fileItem, $totalValue, $lstUnitOfMeasurement, $title, $edit, $key, $items, $totalDocument, $withholding_tax;

    protected $rules = [
        'unitValue'           =>  'required|numeric|min:1',
        'quantity'            =>  'required|numeric|min:0.1',
        'article'             =>  'required',
        'unitOfMeasurement'   =>  'required',
        'taxes'               =>  'required',
        'technicalSpecifications' => 'required'
    ];

    protected $messages = [
        'unitValue.required'          => 'Valor Unitario no puede estar vacio.',
        'unitValue.numeric'           => 'Valor Unitario debe ser numérico.',
        'unitValue.min'               => 'Valor Unitario debe ser mayor o igual a 1.',
        'quantity.required'           => 'Cantidad no puede estar vacio.',
        'quantity.numeric'            => 'Cantidad debe ser numérico.',
        'quantity.min'                => 'Cantidad debe ser mayor o igual a 0.1.',
        'article.required'            => 'Debe ingresar un Artículo.',
        'unitOfMeasurement.required'  => 'Debe seleccionar una Unidad de Medida',
        'taxes.required'              => 'Debe seleccionar un Tipo de Impuesto.',
        'technicalSpecifications.required' => 'Debe ingresar especificaciones técnicas al item.'
    ];

    protected function validationData()
    {
        $this->sanitize();
        return parent::validationData(); // TODO: Change the autogenerated stub
    }

    public function addItem(){
      $this->validate();
      $this->items[]=[
            'id'                       => null,
            'article'                  => $this->article,
            'unitOfMeasurement'        => $this->unitOfMeasurement,
            'technicalSpecifications'  => $this->technicalSpecifications,
            'quantity'                 => $this->quantity,
            'unitValue'                => $this->unitValue,
            'taxes'                    => $this->taxes,
            'totalValue'               => $this->quantity * $this->totalValueWithTaxes($this->unitValue),
            'articleFile'              => $this->articleFile ? $this->articleFile->getRealPath() : null,
      ];
    //   dd($this->items);
      $this->estimateExpense();
      $this->cleanItem();
      $this->emitUp('savedItems', $this->items);
    }

    public function totalValueWithTaxes($value)
    {
        if($this->taxes == 'iva') return $value * 1.19;
        if($this->taxes == 'bh') return isset($this->withholding_tax[date('Y')]) ? round($value / (1 - $this->withholding_tax[date('Y')])) : round($value / (1 - end($this->withholding_tax)));
        return $value;
    }

    public function editItem($key)
    {
        $this->resetErrorBag();
        $this->title                    = "Editar Item Nro ". ($key+1);
        $this->edit                     = true;
        $this->article                  = $this->items[$key]['article'];
        $this->unitOfMeasurement        = $this->items[$key]['unitOfMeasurement'];
        $this->technicalSpecifications  = $this->items[$key]['technicalSpecifications'];
        $this->quantity                 = $this->items[$key]['quantity'];
        $this->unitValue                = $this->items[$key]['unitValue'];
        $this->taxes                    = $this->items[$key]['taxes'];
        $this->key                      = $key;
    }

    public function updateItem()
    {
        $this->validate();
        $this->edit                                         = false;
        $this->items[$this->key]['article']                 = $this->article;
        $this->items[$this->key]['unitOfMeasurement']       = $this->unitOfMeasurement;
        $this->items[$this->key]['technicalSpecifications'] = $this->technicalSpecifications;
        $this->items[$this->key]['quantity']                = $this->quantity;
        $this->items[$this->key]['unitValue']               = $this->unitValue;
        $this->items[$this->key]['taxes']                   = $this->taxes;
        $this->items[$this->key]['totalValue']              = $this->quantity * $this->totalValueWithTaxes($this->unitValue);
        if($this->articleFile) $this->items[$this->key]['articleFile'] = $this->articleFile->getRealPath();
        $this->estimateExpense();
        $this->cleanItem();
        $this->emitUp('savedItems', $this->items);
    }

    public function deleteItem($key)
    {
        if($this->editRF && array_key_exists('id',$this->items[$key])){
          $this->deletedItems[]=$this->items[$key]['id'];
          $this->emitUp('deletedItems', $this->deletedItems);
        }
        unset($this->items[$key]);
        $this->estimateExpense();
        $this->cleanItem();
        $this->emitUp('savedItems', $this->items);
    }

    public function estimateExpense()
    {
        $this->totalDocument = 0;
        foreach($this->items as $item){
          $this->totalDocument = $this->totalDocument + $item['totalValue'];}
    }

    public function cleanItem()
    {
        $this->title = "Agregar Item";
        $this->edit  = false;
        $this->resetErrorBag();
        $this->article = $this->technicalSpecifications = $this->quantity = $this->unitValue = "";
        $this->taxes = $this->budget_item_id = $this->unitOfMeasurement = "";
        $this->articleFile = null;
    }

    public function mount($savedItems)
    {
        $this->totalDocument          = 0;
        $this->lstUnitOfMeasurement   = UnitOfMeasurement::all();
        $this->items                  = array();
        $this->title                  = "Agregar Item";
        $this->edit                   = false;
        $this->editRF                 = false;
        // Porcentaje retención boleta de honorarios según el año vigente
        $this->withholding_tax        = [2021 => 0.115, 2022 => 0.1225, 2023 => 0.13, 2024 => 0.1375, 2025 => 0.145, 2026 => 0.1525, 2027 => 0.16, 2028 => 0.17];
        if(!is_null($savedItems)){
            $this->editRF = true;
            $this->savedItems = $savedItems;
            $this->setSavedItems();
          }
    }

    private function setSavedItems()
    {
        foreach($this->savedItems as $item){
            $this->items[]=[
                'id'                       => $item->id,
                'article'                  => $item->article,
                'unitOfMeasurement'        => $item->unit_of_measurement,
                'technicalSpecifications'  => $item->specification,
                'quantity'                 => $item->quantity,
                'unitValue'                => $item->unit_value,
                'taxes'                    => $item->tax,
                'totalValue'               => $item->expense,
                // 'articleFile'              => $item->articleFile ? $item->articleFile->getRealPath() : null,
          ];
        //   dd($this->items);
          $this->estimateExpense();
        }
    }

    public function render()
    {
        return view('livewire.request-form.item.request-form-items');
    }
}
